evmos/evmos

- go.mod
- go.sum
> Revert "build(deps): bump github.com/tendermint/tm-db from 0.6.4 to 0.6.5"

- docs/guides/keys-wallets/metamask.md
Fix typo at line 47.
Closes: #XXX
______
______
For admin use:
> Update metamask.md - fix typo

- docs/guides/keys-wallets/keyring.md
Fix typo at line 13.
Closes: #XXX
______
______
For admin use:
> Update keyring.md - fix typo

- .bencher/config.yaml
- .gitignore
- CHANGELOG.md
- go.mod
- go.sum
Closes: #XXX
______
______
For admin use:
> release: cherry pick `v0.1.2`

- app/app.go
- app/tps_counter.go
- app/tps_counter_test.go
- cmd/config/observability.go
- cmd/evmosd/main.go
- docs/quickstart/run_node.md
- go.mod
- go.sum
This change implements a TPS (TransactionsPerSecond)
counter that periodically logs the counts of transactions
processes within a regular period, which by default is 10s.
We are able to implement this by incrementing everytime
that (*Evmos).EndBlocker is invoked, which is for every block
commited.
Updates #73
> app: implement a TransactionsPerSecond (TPS) counter for (*Evmos)

- docs/.vuepress/config.js
- docs/guides/tools/hardhat.md
Closes: #ENG-225
Updates rpc url to the one with ssl enabled
______
______
For admin use:
> docs: update rpc url

- docs/.vuepress/config.js
- docs/guides/tools/hardhat.md
Reserving `*.rpc.evmos.org` for mainnet URLs only. Using `*.rpc.evmos.dev` for testnet urls
______
______
For admin use:
> docs: update testnet rpc url to *.evmos.dev

- docs/guides/keys-wallets/keplr.md
Closes: #XXX
______
______
For admin use:
> Add note that only secp256k1 keys are supported

- .github/workflows/security.yml
Closes: #255
Adding `security.yml` in `.github/workflows` to enable [Gosec](https://linear.app/tharsis/issue/ENG-255/add-gosec-github-action-to-check-security-issues-on-sdk-based-chains)
______
______
For admin use:
> ci: add gosec to PRs and main

- docs/testnet/join.md
Fetches records from seeds.txt and random 10 records from peers.txt and adds them to the node config
______
- [+] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [+] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [+] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [+] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [+] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [+] Added  relevant `godoc` …
> Get seeds and peers from repo and update config

- .github/workflows/docker-push.yml
- Makefile
- docs/quickstart/installation.md
Closes: #ENG-295
- Add github action to upload the docker container to docker hub for when we have `v*` tags
______
______
For admin use:
> ci: build docker containers and push to docker hub

- docs/quickstart/binary.md
Grammar fix at line 65
Closes: #XXX
______
______
For admin use:
> Grammar fix

- x/intrarelayer/spec/06_events.md
Fixed a little typo at 06_events.md file
> fixed a little typo (06_events.md)

- x/intrarelayer/spec/README.md
This PR updates the documentation on [evmos docs](https://evmos.dev/)
> Docs(Intrarelayer): Add Use Cases to abstract

- .github/workflows/docker-push.yml
- CHANGELOG.md
- Makefile
- docs/quickstart/installation.md
Closes: #ENG-304
- change dockerhub username to tharsishq
______
______
For admin use:
> ci: rename docker hub account tharsislabs -> tharsishq

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> release: v0.4.0 changelog

- docs/basics/accounts.md
Renames binary name from ethermintd to evmosd in docs.
______
______
For admin use:
> Change ethermintd -> evmosd in docs

- app/app.go
Closes: #XXX
______
______
For admin use:
> Olympus-Mons-v0.4.1 Upgrade handler

- app/app.go
- app/test_helpers.go
- go.mod
- go.sum
- x/erc20/types/msg.go
- x/erc20/types/proposal.go
This reverts commit 4a4aed1c8383e101b47731718029ac688cdcaf3e.
Closes: #XXX
______
______
For admin use:
> Revert "deps: IBC v3"

- docs/intro/overview.md
Closes: #XXX
______
This PR fixes a typo in the documentation for evmos, so doesn't need most of the the points above
______
For admin use:
> fix: typo in evmos doc

- CHANGELOG.md
- cmd/evmosd/init.go
- cmd/evmosd/root.go
Closes: #XXX
______
______
For admin use:
> add state sync snapshots to default app.toml

- x/incentives/client/cli/query.go
- x/incentives/client/cli/tx.go
Closes: #XXX
Fixes the flipped logic on the address checks on the incentives cli
______
______
For admin use:
> fix incentives cli

- x/incentives/proposal_handler.go
Fixes string formatting and event key.
> feat(incentives): fix events

- x/incentives/client/cli/query.go
Minor fix that makes CLI descriptions more readable.
> feat(incentives): fix cli query descriptions

- app/app.go
Closes: #XXX
This PR fixes the problems when running the init.sh script with this module.
It creates the ClaimKeeper before calling the Hooks method
It reorders the genesis execution to populate the Claim Params before executing the Staking Hooks.
______
______
For admin use:
> fix object order on app.go file

- x/claim/keeper/claim_test.go
- x/claim/keeper/keeper_test.go
Closes: [#ENG-421](https://linear.app/tharsis/issue/ENG-421/keepergo-unit-tests-getter-and-setters)
______
______
For admin use:
> Add back claim clawback test

- init.sh
Closes: #XXX
______
______
For admin use:
> setting the claiming supply directly to the bank module

- init.sh
Closes: #XXX
______
I have...
I have...
______
I have...
> deps:  update evm denom to aevmos

- docs/tools/explorers.md
fix spelling from `Cosmoss` to `Cosmos`
______
- Couldn't find the `development` branch as specified [here](https://github.com/tharsis/evmos/blob/main/CONTRIBUTING.md#pr-targeting) 
- didn't add a changelog because I'm doing this from the github UI
I have...
- [] added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [] targeted the correct branch (see [PR Targeting](https://github.com/tharsis/evmos/blob/main/CONTRIBUTING.md#pr-targeting))
- [] provided a link in the PR description to the relevant issue or specification
- [] confirmed all required CI checks have passed
I have...
- [] …
> fix: spelling

- x/README.md
- x/epochs/spec/README.md
- x/inflation/spec/README.md
This PR fixes the inflation title in the module list and sorts the module list alphabetically.
> spec(evmos): fix module list

- app/sigverify_test.go
Tests to verify gas costs and check key types no longer supported actually fail for `SigVerificationGasConsumer`
Closes: #XXX
______
I have...
I have...
______
I have...
> tests: add sigverify tests

- app/ante/vesting.go
- x/vesting/keeper/integration_test.go
- x/vesting/types/clawback_vesting_account.go
- bug(vesting): fail delegation if account is locked
- bug(vesting): fix error message
- bug(vesting): make locked && vested coins delegatable again
> bug(vesting): refactor `HasLockedCoins` 

- docs/testnet/join.md
Closes: #XXX
______
I have...
I have...
______
I have...
> (doc): add cd step to join doc

- docs/tools/explorers.md
Closes: #XXX
______
I have...
I have...
______
I have...
> docs: update explorers urls

- docs/guides/validators/setup.md
Closes: #XXX
______
I have...
I have...
______
I have...
> docs: update guides/validator_setup

- x/claims/keeper/abci_test.go
Ref: https://github.com/tharsis/evmos/pull/298#discussion_r817110426
@khoslaventures
> claims: update test case names

- x/erc20/keeper/evm.go
- x/erc20/keeper/keeper.go
- x/erc20/keeper/mint.go
- x/erc20/keeper/msg_server.go
- x/erc20/keeper/proposals.go
- x/erc20/keeper/proposals_test.go
- x/erc20/types/errors.go
- x/erc20/types/interfaces.go
- x/incentives/keeper/keeper.go
- x/incentives/types/interfaces.go
- disable coin registration for EVM denom to prevent fragmentation with wrapped tokens
- clean up errors
______
I have...
I have...
______
I have...
> erc20: disable evm denom registration

- CHANGELOG.md
Closes: #XXX
______
I have...
I have...
______
I have...
> release: v1.1.0

- CHANGELOG.md
- release: v1-alpha1 changelog (#251)
- release: v1.0.0-beta1 changelog (#273)
- release: v1.0.0 final (#300)
- release: v1.1.0 (#324)
> release: v1.1 changelog

- CHANGELOG.md
- cmd/evmosd/cmd_test.go
- cmd/evmosd/root.go
- go.mod
- go.sum
- fix conflicts
- conflicts
Closes: #XXX
______
I have...
I have...
______
I have...
> release: v1.1.1

- docs/guides/upgrades/upgrade_node.md
shouldn't use go get anymore, it changes go.mod and go.sum for the project directory you're in
______
I have...
I have...
______
I have...
> docs: use `go install` for cosmovisor

- CHANGELOG.md
- app/app.go
- app/forks.go
- app/upgrades/v2/constants.go
- go.mod
- go.sum
- x/claims/keeper/migrations.go
- x/claims/migrations/v2/migration.go
- x/claims/module.go
- x/erc20/migrations/v2/migration.go
- x/erc20/module.go
- release: v1.1.0 (#324)
- release: v1.1.1 (#346)
- app: upgrade v1.1.2 logic to v2 (#354)
> release: v1.1.2 changelog

- docs/tools/explorers.md
Hi, we'd love to have a link ATOMScan for Evmos added to the docs!
______
I have...
I have...
______
I have...
> Adds ATOMScan explorer to Evmos docs

- CHANGELOG.md
- x/erc20/keeper/proposals.go
- x/erc20/keeper/token_pairs.go
- x/erc20/keeper/token_pairs_test.go
> fix: delete token pair

- docs/guides/tools/hardhat.md
Closes: #XXX
______
I have...
I have...
______
I have...
> change to a working testnet rpc url

- CHANGELOG.md
- x/claims/keeper/claim.go
- x/claims/keeper/hooks.go
- x/claims/keeper/ibc_callbacks.go
- x/claims/keeper/ibc_callbacks_test.go
- x/claims/keeper/keeper.go
Closes: #XXX
______
I have...
I have...
______
I have...
> fix: EVM claims migration

- x/claims/spec/01_concepts.md
- x/claims/spec/README.md
This PR adds the ibc transfer concept to the specs
> spec(claims): Add ibc action to concepts

- x/claims/types/claim_record_test.go
- x/incentives/keeper/grpc_query.go
- x/incentives/keeper/grpc_query_test.go
- x/inflation/keeper/inflation.go
- x/inflation/keeper/inflation_test.go
Closes: #XXX
______
I have...
I have...
______
I have...
> imp: bump coverage

- CHANGELOG.md
- go.mod
- go.sum
Closes: #XXX
______
I have...
I have...
______
I have...
> deps: bump ibc-go to v3

- cmd/evmosd/testnet.go
> Fix testnet init chain error

- x/claims/keeper/claim_test.go
- x/claims/keeper/ibc_callbacks.go
- x/claims/keeper/ibc_callbacks_test.go
- x/claims/types/interfaces.go
Closes: #XXX
______
I have...
I have...
______
I have...
> claims: restrict claiming for blocked addresses

- app/app.go
- x/claims/ibc_middleware.go
- x/claims/keeper/hooks.go
- x/recovery/ibc_middleware.go
Closes: #XXX
______
I have...
I have...
______
I have...
> imp: rename claims ibc module to middleware

- CHANGELOG.md
- app/ante/handler_options.go
- app/app.go
- go.mod
- go.sum
Closes: #XXX
______
I have...
I have...
______
I have...
> deps: bump ethermint to v0.12.0

- x/recovery/keeper/ibc_callbacks_integration_test.go
Replaces #407 
Closes ENG-61
______
I have...
I have...
______
I have...
> imp: recovery integration IBC tests

- docs/guides/keys-wallets/keyring.md
- docs/guides/keys-wallets/metamask.md
- docs/guides/localnet/single_node.md
- docs/guides/localnet/testnet_cmd.md
- docs/guides/validators/faq.md
- docs/guides/validators/setup.md
- docs/mainnet/join.md
- docs/quickstart/binary.md
Closes: #XXX
______
I have...
I have...
______
I have...
> docs: add warnings for `keyring-backend test`

- CHANGELOG.md
- app/forks.go
- go.mod
- go.sum
Closes: #XXX
______
I have...
I have...
______
I have...
> deps: bump Cosmos SDK to v0.45.2

- CHANGELOG.md
- app/upgrades/README.md
- x/claims/keeper/hooks_test.go
- release: v3.0.0 changelog (#433)
- release: v3.0.0-beta1 (#459)
Closes: #XXX
______
I have...
I have...
______
I have...
> misc: changelog and fix test

- x/fees/client/cli/query.go
- x/fees/client/cli/tx.go
Closes: #XXX
______
I have...
I have...
______
I have...
> [ENG-128] Fee distribution module - add cli commands for queries and transactions

- x/claims/genesis_test.go
- x/claims/keeper/abci.go
- x/claims/keeper/abci_test.go
- x/claims/keeper/claim_test.go
- x/claims/keeper/grpc_query_test.go
- x/claims/keeper/hooks_test.go
- x/claims/keeper/invariants_test.go
includes comments from https://github.com/tharsis/evmos/pull/510
> impr(claims): move claimsRecords deletion out of iteration

- CHANGELOG.md
- cmd/evmosd/root.go
Closes: #XXX
Defines a default `min-gas-prices` of `0.0025aevmos` for mainnet
______
I have...
I have...
______
I have...
> imp: update default min-gas-prices

- x/erc20/keeper/evm_hooks.go
- x/erc20/keeper/proposals.go
- x/erc20/types/errors.go
- x/erc20/types/msg.go
- x/erc20/types/proposal.go
- x/erc20/types/utils.go
- x/erc20/types/utils_test.go
Closes: #XXX
______
I have...
I have...
______
I have...
> audit(erc20): add types tests and update comments

- docs/developers/connect.md
Closes: #570
______
I have...
I have...
______
I have...
> Correct testnet endpoint URLs

- docs/package.json
Closes: #XXX
______
I have...
I have...
______
I have...
> docs: upgrade deps

- .mergify.yml
Closes: ENG-237
______
I have...
I have...
______
I have...
> ci: update mergify config

- CHANGELOG.md
- app/ante/handler_options.go
- go.mod
- go.sum
Part of [ENG-234](https://linear.app/evmos/issue/ENG-234/release-ethermint-v015)
> bump(ethermint): v0.15.0

- app/upgrades/v4/constants.go
- app/upgrades/v4/upgrades.go
Closes: #XXX
______
I have...
I have...
______
I have...
> release: set v4 upgrade heights

- CHANGELOG.md
Closes: #XXX
______
I have...
I have...
______
I have...
> release: v3.0.1 changelog

- CHANGELOG.md
- x/erc20/keeper/migrations.go
- x/erc20/migrations/v2/migration.go
- x/erc20/migrations/v2/migration_test.go
- x/erc20/module.go
Revert #556 (doing it manually since I can't click Revert for some reason)
______
I have...
I have...
______
I have...
> fix: readd erc20 migration logic

- CHANGELOG.md
- app/upgrades/v4/constants.go
Closes: #XXX
______
I have...
I have...
______
I have...
> release: update v4 upgrade info

- proto/evmos/inflation/v1/inflation.proto
Closes: #XXX
______
I have...
I have...
______
I have...
> Correct inflation.proto typo

- docs/.vuepress/config.js
Closes: #XXX
______
I have...
I have...
______
I have...
> Update docs config w/ new Algolia API key

- docs/developers/explorers.md
This PR fixes wrong formatting in the docs
> bug(specs): fix explorer mainnet testnet table

- docs/validators/governance/best_practices.md
Closes: #XXX
______
I have...
I have...
______
I have...
> docs: Update deposit amount in best_practices.md

- docs/developers/connect.md
Adds a JSON RPC API for Evmos maintained by the Stakely team.
______
I have...
I have...
______
I have...
> docs: add Stakely json rpc

- docs/developers/connect.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Add another notional RPC to the docs

- docs/protocol/telemetry.md
Part of: https://linear.app/evmos/issue/ENG-422/add-observability-telemetry-on-ethermint
> specs(telemetry): add ethermint endpoints

- Dockerfile
Closes: #XXX
______
I have...
I have...
______
I have...
> Change update method in Dockerfile

- app/ante/handler_options.go
- x/fees/keeper/integration_test.go
Closes: ENG-408 https://linear.app/evmos/issue/ENG-408/update-evmos-antehandler
______
I have...
I have...
______
I have...
> ante: MinGasPrices AnteHandler decorator

- .github/dependabot.yml
- .mergify.yml
- app/app.go
- app/upgrades/v5/constants.go
- app/upgrades/v5/upgrades.go
- app/upgrades/v5/upgrades_test.go
Closes: #XXX
______
I have...
I have...
______
I have...
> fix(app): fix v5 upgrade handler globals

- CHANGELOG.md
- app/app.go
- app/upgrades/v5/constants.go
- app/upgrades/v5/upgrades.go
- app/upgrades/v5/upgrades_test.go
Closes: #XXX
______
I have...
I have...
______
I have...
> release: update consensus params

- docs/.vuepress/config.js
- docs/README.md
- docs/developers/connect.md
- docs/protocol/ibc.md
- docs/validators/mainnet.md
- docs/validators/testnet.md
- docs/validators/upgrades/upgrades.md
Closes: #XXX
______
I have...
I have...
______
I have...
> docs: update release and general docs

- docs/developers/explorers.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Add NG Explorers

- CHANGELOG.md
- cmd/evmosd/root.go
Closes: #XXX
______
I have...
I have...
______
I have...
> imp(cmd): update default Tendermint config

- docs/validators/governance/best_practices.md
- docs/validators/governance/community_pool.md
- docs/validators/governance/overview.md
- docs/validators/governance/param_change.md
- docs/validators/governance/process.md
- docs/validators/governance/submitting.md
- docs/validators/snapshots_archives.md
updated markdown files in docs/validators/governance to incorporate information from Cosmos Hub documentation, along with suggestions for those submitting ERC-20 module proposals.
______
I have...
I have...
______
I have...
> updated governance docs

- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- Makefile
- README.md
Closes: #XXX
______
I have...
I have...
______
I have...
> imp(ci): use goreleaser Github Action

- CHANGELOG.md
This PR adds the changelog from release `v6.0.0` to `main`
> release(v6): add changelog from release

- docs/validators/testnet.md
Closes: #XXX
______
I have...
I have...
______
I have...
> change testnet genesis download path in docs

- .github/workflows/super-linter.yml
Closes: #XXX
______
I have...
I have...
______
I have...
> imp(ci): add super linter

- x/feesplit/keeper/msg_server_test.go
- x/feesplit/keeper/params_test.go
- x/feesplit/types/fee_split_test.go
- x/feesplit/types/params.go
FeeSplit test coverage
Closes: #XXX
______
I have...
I have...
______
I have...
> [ENG-451] FeeSplit tests

- .github/workflows/semgrep.yml
- ENG-567
______
I have...
I have...
______
I have...
> [ENG-567] fix(ci): semgrep action

- x/feesplit/keeper/integration_test.go
- x/feesplit/keeper/msg_server.go
- x/feesplit/keeper/msg_server_test.go
- x/feesplit/types/msg.go
- x/feesplit/types/msg_test.go
Fix: Allow update withdrawer back to deployer.
Fix: Old Withdrawer map entry was not beeing correctly deleted after an update.
Closes: #XXX
______
I have...
I have...
______
I have...
> [ENG-451] Feesplits fixes

- README.md
Fix some links redirecting to documentation in `README`
Closes: (I consider this fix didn't need to open an issue as the fix was trivial and evident, let me know if you don't make exception on this process)
______
I have...
I have...
______
I have...
> chore(`README.md`): fix documentation links

- .mergify.yml
- CHANGELOG.md
- go.mod
- go.sum
Closes: #XXX
______
I have...
I have...
______
I have...
> deps: bump ethermint to v0.17.2

- docs/.vuepress/config.js
Adding GA to our docs increases understanding of how event sponsorships work with our docs access.
______
Just reformatted based on linting rules as well.
> added google analytics

- docs/developers/json-rpc/server.md
This PR adds quick changes for making the intro  page on the json rpc server easier to understand by providing some more basic information what problem the server solves.
> docs(json-rpc server): make more reader friendly

- docs/.vuepress/config.js
Moved back from using Google Analytics 4 to older system in order to make GA work.
> change to old UA attempts

- CHANGELOG.md
Closes: #XXX
______
I have...
I have...
______
I have...
> chore(docs): update changelog

- app/forks.go
- app/upgrades/v7/constants.go
Closes: #XXX
______
I have...
I have...
______
I have...
> chore(app): set up v7 fork upgrade height

- docs/.vuepress/config.js
- init.sh
- Update main net evmosd release version
- Remove un-necessary param in `init.sh`
- Add some more lines of comment to `init.sh`
______
I have...
I have...
______
I have...
> docs: update mainnet release version + add comments to init.sh

- app/app.go
- app/upgrades/v8/constants.go
- app/upgrades/v8/upgrades.go
- app/upgrades/v8/upgrades_test.go
Closes: #XXX
______
I have...
I have...
______
I have...
> chore(release): add upgrade handler and store upgrade logic for feesplit module

- CHANGELOG.md
- app/upgrades/v8/constants.go
This PR adds a changelog for the `v8` release branch and sets the upgrade heights
> release: v8.0.0 changelog & upgrade heights

- docs/protocol/telemetry.md
- go.mod
This PR adds the feesplit telemetry endpoint to Evmos.dev
> docs(telemetry): add feesplit endpoint

- LICENSE
Closes: #XXX
______
I have...
I have...
______
I have...
> chore: update license to LGPLv3

- CHANGELOG.md
- Dockerfile
- networks/local/evmos/Dockerfile
- Update docker base image from golang:stretch to golang:1.18.5-bullseye
- Expose other relevant ports in dockerfile: 8545, 8546, 9090
Closes: #XXX
______
I have...
I have...
______
I have...
> [ENG-684] - (build) update docker base image

- CHANGELOG.md
Closes: #XXX
______
I have...
I have...
______
I have...
> `v8.1.0` Release changelog

- .github/workflows/security.yml
- app/app.go
- x/incentives/genesis.go
Closes: #XXX
______
I have...
I have...
______
I have...
> fix(ci): fix gosec reported vulnerabilities

- docs/validators/run_relayer.md
Closes: # NA
______
I have...
I have...
______
I have...
> Documentation : Keytype for running Hermes is missing

- docs/developers/connect.md
Add mainnet rpc/grpc/api/jsonrpc by NodeStake
Closes: #XXX
______
I have...
I have...
______
I have...
> Add mainnet rpc/grpc/api/jsonrpc Documentation

- docs/.vuepress/config.js
Updates docs websites config file to allow passing sensitive information through environment variables rather than being hardcoded in the code. This prevents key leaks.
______
I have...
I have...
______
I have...
> Allow docs website to get variables through env

- Makefile
- Releasing section in Makefile is repeated and is identical in two places
Closes: #XXX
______
I have...
I have...
______
I have...
> Remove duplicate releasing section in Makefile

- .github/workflows/security.yml
- Uncomment upload sarif as https://github.com/cosmos/gosec/issues/38 is fixed
Closes: #XXX
______
I have...
I have...
______
I have...
> [ENG-807] - Uncomment upload sarif step in security workflow

- CHANGELOG.md
- app/app.go
- app/upgrades/v8_2/upgrades.go
Closes: #XXX
______
I have...
I have...
______
I have...
> chore(app): v8.2.0 upgrade handler + store upgrade

- docs/developers/connect.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Update connect.md to include Silk Nodes

- app/app.go
- app/upgrades/v8_2/upgrades.go
Delete param set for revenue on upgrade handler
Closes: #XXX
______
I have...
I have...
______
I have...
> imp(app): delete unnecessary upgrade logic

- CHANGELOG.md
- app/upgrades/v8_2/constants.go
Closes: #XXX
______
I have...
I have...
______
I have...
> chore(app): set upgrade height for v8.2.0

- docs/developers/connect.md
adding Blast Api by Bware Labs to the documentation
Closes: #XXX
______
I have...
I have...
______
I have...
> add Blast public APIs to the Quick Connect Doc

- docs/developers/clients.md
> Docs: typos

- docs/developers/connect.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Add PublicNode

- docs/developers/connect.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Add testnet endpoints (RPC,REST,gRPC) for Qubelabs

- CHANGELOG.md
- x/claims/keeper/abci.go
- x/claims/keeper/abci_test.go
- x/claims/keeper/claim_test.go
- x/claims/keeper/integration_test.go
- x/claims/spec/03_state_transitions.md
- x/claims/types/claims_record.go
Fix logic on ClawbackEmptyAccounts by checking for:
- EthAccount types only
- Only remove accounts with empty balances on all denominations
- Only clawback accounts with same balances as dust sent in genesis
Closes: https://linear.app/evmos/issue/ENG-869/fix-airdrop-clawback-code
______
I have...
I have...
______
I have...
> fix ClawbackEmptyAccounts logic

- x/revenue/spec/08_clients.md
Fixing typo. Merging with admin rights
> fix missing rename to revenue in spec

- x/inflation/spec/05_parameters.md
The on-chain parameter keys of the `x/inflation` module are different from the ones in the documentation.
For example, the `EnableInflation` key shown in: https://docs.evmos.org/modules/inflation/05_parameters.html
should be `ParamStoreKeyEnableInflation`: https://github.com/evmos/evmos/blob/main/x/inflation/types/params.go#L20
When I created a gov proposal to change the parameter, I had to use `ParamStoreKeyEnableInflation` so that the transaction went through successfully. Otherwise, I would get `panic redacted` error.
I set the target as `main` because it is just a documentation update. 
Closes: NA
______
I have...
Code …
> [Documentation] Update inflation param keys

- cmd/evmosd/root.go
- go.mod
- go.sum
This PR bumps ibc-go in evmos to v3.3.0
______
I have...
I have...
______
I have...
> ibc-go v3.3.0

- x/revenue/keeper/integration_test.go
Forgot to commit this change in https://github.com/evmos/evmos/pull/958. Just removing the comment.
> chore(revenue): remove fixme

- CHANGELOG.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Update CHANGELOG.md for changes in #993

- app/app_test.go
Added public key creation error check to test helpers  to resolve [alert 
2543](https://github.com/evmos/evmos/security/code-scanning/2543) as a final goal 
to close [ENG-904](https://linear.app/evmos/issue/ENG-904/fix-gosec-ci-reports)
Closes: ENG-904
______
I have...
I have...
______
I have...
> test(app_test): add pubkey creation error check

- CHANGELOG.md
- cmd/evmosd/root.go
Add new `prune` command to cli
______
I have...
I have...
______
I have...
> imp(cmd): Add pruning cmd

- docs/validators/snapshots_archives.md
add Notional pebbledb snapshots to docs
______
I have...
I have...
______
I have...
> docs: add Notional pebbledb snapshots

- SECURITY.md
Closes: #XXX
______
I have...
I have...
______
I have...
> chore(docs): update SECURITY.md

- docs/developers/connect.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Added Validatrium endpoints

- docs/protocol/moduleaccounts.md
Adding `evm` && `ibc` module accounts to docs.
Closes: [ENG-844](https://linear.app/evmos/issue/ENG-844/add-missing-module-accounts-to-docs)
______
I have...
I have...
______
I have...
> docs(modulaccounts): added missing modules

- app/upgrades/v9_1/upgrades_test.go
- x/erc20/client/cli/utils_test.go
- x/erc20/keeper/integration_test.go
Closes: #XXX
______
I have...
I have...
______
I have...
> chore: run gofumpt

- CHANGELOG.md
- app/upgrades/v10/constants.go
Closes: #XXX
______
I have...
I have...
______
I have...
> release: v10.0.0-rc1 changelog and upgrade handler

- CHANGELOG.md
- x/erc20/keeper/mint.go
- x/erc20/keeper/params.go
- x/erc20/keeper/token_pairs.go
- x/erc20/proposal_handler.go
Adds util functions for usage in automatic coin conversion and migration logic
______
I have...
I have...
______
I have...
> imp(erc20): util functions

- docs/developers/connect.md
Updated POKT entry to include close square-bracket for their link and moved them to the bottom of the list to be fair to others (historically others have added to the bottom rather than to the top)
Closes: #XXX
______
I have...
I have...
______
I have...
> docs: sort public endpoints from older to latest

- docs/protocol/telemetry.md
Closes: #XXX
______
I have...
I have...
______
I have...
> Update telemetry.md with correct url to cosmos telemetry docs

- CHANGELOG.md
- docs/about/intro/audits.md
Closes ENG-1030
This PR adds an audit page to [docs.evmos.org](docs.evmos.org).
> docs: Add audits page

- .gitleaksignore
- local_node.sh
PR title self describing.
---
Closes: [ENG-1083](https://linear.app/evmos/issue/ENG-1083/add-gitleaksignore-to-evmos-andand-ethermint)
> chore: add gitleaks ignore

- CHANGELOG.md
- app/app.go
This PR sets the default `File` Listener from Cosmos SDK's [ADR38](https://docs.cosmos.network/v0.47/architecture/adr-038-state-listening)
______
I have...
I have...
______
I have...
> chore(app): store listener

- cmd/evmosd/root.go
Closes: #XXX
______
I have...
I have...
______
I have...
> fix(cmd): add missing GetAuxToFeeCommand

- CHANGELOG.md
- app/app.go
- cmd/evmosd/root.go
Closes ENG-1018
Closes ENG-1105
______
I have...
I have...
______
I have...
> fix(cmd): set snapshot config to application

- app/app.go
Closes: #XXX
______
I have...
I have...
______
I have...
> minor ica patch

- docs/users/wallets/keplr.md
Closes: #XXX
______
I have...
I have...
______
I have...
> fix: update Keplr docs to remove (beta)

- local_node.sh
Closes: Linear [#973](https://linear.app/evmos/issue/ENG-973/add-flag-on-initsh-to-enable-http-server-locally).
This PR enables the http server by default when starting a local node to make all endpoints available. This improves the local development experience, and unless there are good reasons otherwise (e.g. performance), this should be the default.
______
I have...
I have...
______
I have...
> fix: enable HTTP server on localnode by default

- x/vesting/client/cli/tx.go
`tx vesting create-clawback-vesting-account` commands show an example json input file but there was a typo, must be `periods` instead of `period`
______
I have...
I have...
______
I have...
> style: fix vesting example file

- cmd/evmosd/root.go
Closes: #XXX
Set the encoding config for the `EIP-712` module so it can be used during verification. If this is not implemented, users will encounter nil pointer errors on verification.
______
I have...
I have...
______
I have...
> fix: set encoding config from root for EIP-712 verification from key

- x/erc20/keeper/ibc_callbacks.go
- x/ibc/transfer/keeper/msg_server.go
Closes: #XXX
______
I have...
I have...
______
I have...
> imp(erc20): ignore gas costs on IBC transfer for automatic ERC20 conversion

- app/app.go
- cmd/evmosd/root.go
Closes: #XXX
______
I have...
I have...
______
I have...
> Move encoding config setup from command line to app

- x/ibc/transfer/keeper/msg_server.go
Closes: #XXX
______
I have...
I have...
______
I have...
> fix(erc20): automatic conversion using 'erc20/<contract_address>'

- cmd/evmosd/root.go
Closes: #XXX
EIP-712 encoding config initialization in `app.go` is not called when running `evmosd` command line arguments. We add the same initialization here to ensure that the module is set up in both cases.
______
I have...
I have...
______
I have...
> Add EIP-712 encoding config init back to root

- x/erc20/keeper/ibc_callbacks.go
- x/erc20/keeper/ibc_callbacks_integration_test.go
- x/ibc/transfer/keeper/msg_server.go
- x/ibc/transfer/keeper/msg_server_test.go
Closes: #XXX
______
I have...
I have...
______
I have...
> fix(erc20): update token denom on msg

- Makefile
Add build flag `-gcflags "all=-N -l"` for unoptimized compile used for remote debugging.
This flag is added when passing `COSMOS_BUILD_OPTIONS=nooptimization`
Closes: #XXX
______
I have...
I have...
______
I have...
> debug(app): add flag for remote debugging compile

- .github/workflows/upgrade-test.yml
Closes: #XXX
______
I have...
I have...
______
I have...
> fix: add e2e upgrade test to PRs only for branches release

- docs/.vuepress/config.js
- docs/developers/explorers.md
- docs/developers/testnet/faucet.md
- Update block explorers name, urls
- Fix broken link
______
I have...
I have...
______
I have...
> docs: update block explorers

- local_node.sh
Closes: #XXX
______
I have...
I have...
______
I have...
> Enable metrics on `local_node.sh`

- CHANGELOG.md
- app/upgrades/v10/constants.go
- go.mod
- go.sum
Trying to get release `v10.0.0` ready. In this PR:
- Updated changelog to new version and date
- Updated constants
______
I have...
I have...
______
I have...
> Release `v10.0.0`

- app/app.go
- x/inflation/keeper/migrations.go
- x/inflation/migrations/v2/migrate.go
- x/inflation/migrations/v2/migrate_test.go
- x/inflation/migrations/v2/types/params.go
- x/revenue/migrations/v2/migrate.go
Adds the missing `Keytables` when adding the `Subspace` to perform params migration. Additional small issues with keys in the `inflation` module were fixed.
Closes: #XXX
______
I have...
I have...
______
I have...
> fix: add missing Subspace Keytables

- docs/.vuepress/config.js
- x/inflation/spec/01_concepts.md
- x/inflation/spec/03_hooks.md
Changes in `x/inflation` module docs according to `EpochMintProvision` calculation changes
Closes: ENG-1274
https://linear.app/evmos/issue/ENG-1274/update-evmos-docs
> fix: changed inflation docs

- app/app.go
- x/claims/migrations/v3/migrate.go
- x/claims/migrations/v3/migrate_test.go
- x/claims/types/interfaces.go
- x/erc20/keeper/migrations_test.go
- x/erc20/migrations/v3/migration.go
- x/erc20/migrations/v3/migration_test.go
- x/erc20/types/interfaces.go
- x/incentives/migrations/v2/migrate.go
- x/incentives/migrations/v2/migrate_test.go
- x/incentives/types/interfaces.go
- x/inflation/keeper/migrations.go
- x/inflation/keeper/migrations_test.go
- x/inflation/migrations/v2/migrate.go
- x/inflation/migrations/v2/migrate_test.go
- x/inflation/migrations/v2/types/params.go
- x/inflation/types/interfaces.go
- x/recovery/migrations/v2/migrate.go
- x/recovery/migrations/v2/migrate_test.go
- x/recovery/types/interfaces.go
- x/revenue/migrations/v2/migrate.go
- x/revenue/migrations/v2/migrate_test.go
- x/revenue/types/interfaces.go
This PR localizes the `WithKeyTable` method from the `Subspace` in the migration folder of each of the modules that have deprecated x/params. It's used solely for migration and is part of the `LegacySubspace` interface. Previously it was all added in the `app.go`.
Closes: #XXX
______
I have...
I have...
______
I have...
> fix: localize WithKeyTable in each module's migration logic

- app/upgrades/v11/upgrades.go
Closes: #XXX
______
I have...
I have...
______
I have...
> fix(upgrade): ICA Host params

- .github/PULL_REQUEST_TEMPLATE.md
The pull request template includes a checklist, that is not used by regular contributors.  This PR hides the checklist by default.
> impr: update pull request template to hide checklist by default

- app/upgrades/v11/upgrades.go
> imp(upgrade): update testnet reward distr logic

- x/inflation/keeper/grpc_query.go
> nit: update comment on `InflationRate` for grpc

- app/upgrades/v11/accounts.go
Updates the participant address for testnet rewards
----
Closes ENG-1316
> fix: update participant address for testnet reward

- CHANGELOG.md
- go.mod
- go.sum
Uses informal's tendermint fork
I have...
`CHANGELOG.md`
prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
Targeting](https://github.com/evmos/evmos/blob/main/CONTRIBUTING.md#pr-targeting))
I have...
______
I have...
-->
> fix: use informal tendermint

- docs/developers/connect.md
Add MMS endpoints
Add following Evmos endpoints to documentation:
https://api-evmos.mms.team:443	
https://grpc-evmos.mms.team:443	
https://rpc-evmos.mms.team:443	
https://jsonrpc-evmos.mms.team:443
----
Closes #XXX
> Update connect.md with MMS endpoints

- docs/developers/guides/cosmos_coin_registration.md
After going through the [Cosmos coin registration guide](https://docs.evmos.org/developers/guides/cosmos_coin_registration.html) today I've improved some formatting, fixed some typos and introduced semantic line breaks to the markdown file for improved VCS handling and readability in a code editor.
> imp (docs): improve cosmos coin registration guide

- tests/e2e/upgrade/manager.go
- tests/e2e/upgrade/node.go
- tests/e2e/upgrade/upgrade-init.sh
- tests/e2e/upgrade/utils.go
This PR addresses shellcheck comments, improves readibility and the used language in some docstrings in the upgrade test suite.
> imp (tests): address shellcheck comments and improve doc strings in upgrade tests

- CHANGELOG.md
- app/upgrades/v11/constants.go
> chore(upgrade): changelog and const

- app/app.go
- cmd/evmosd/root.go
- go.mod
- go.sum
This PR bumps Ethermint to [v0.21.0-rc2](https://github.com/evmos/ethermint/releases/tag/v0.21.0-rc2).
> chore (deps): bump Ethermint to v0.21.0-rc2

- CHANGELOG.md
> chore: v11-rc2 changelog

- app/upgrades/v11/upgrades.go
> fix(upgrade): remove deletion of recovery module from mainnet upgrade

- CHANGELOG.md
- go.mod
- go.sum
This PR bumps the Ethermint version to [v0.21.0](https://github.com/evmos/ethermint/releases/v0.21.0).
> chore (deps): bump ethermint to v0.21.0

- ibc/testing/chain.go
- ibc/testing/coordinator.go
- ibc/testing/endpoint.go
- ibc/testing/path.go
- testutil/integration.go
- x/claims/keeper/ibc_callbacks_ibc_suite_test.go
- x/claims/keeper/integration_test.go
- x/erc20/keeper/ibc_callbacks_integration_test.go
- x/erc20/keeper/integration_test.go
- x/erc20/keeper/keeper_test.go
- x/recovery/keeper/ibc_callbacks_integration_suite_test.go
- x/recovery/keeper/ibc_callbacks_integration_test.go
- x/revenue/keeper/integration_test.go
Fix tests when using the DynamicFeeChecker for cosmos txs
----
Closes https://linear.app/evmos/issue/ENG-1428/fix-tests-when-implementing-dynamicfeechecker
> chore(tests) fix tests for DynamicFeeChecker

- app/ethtest_helper.go
EthSetup helper that should help setup Testing Suites for other soon to be migrated modules to use
----
Closes #XXX
> Add app test helper

- x/evm/statedb/access_list.go
- x/evm/statedb/config.go
- x/evm/statedb/interfaces.go
- x/evm/statedb/journal.go
- x/evm/statedb/mock_test.go
- x/evm/statedb/state_object.go
- x/evm/statedb/statedb.go
- x/evm/statedb/statedb_test.go
- x/evm/vm/geth/geth.go
- x/evm/vm/geth/precompiles.go
- x/evm/vm/interface.go
This PR only drags the `x/evm/statedb/*` and `x/evm/vm` folders. No imports where updated
----
Closes #XXX
> Migrate `x/evm/statedb` and `x/evm/vm` folders from Ethermint

- x/evm/client/cli/query.go
- x/evm/client/cli/tx.go
- x/evm/client/cli/utils.go
- x/evm/client/cli/utils_test.go
- x/feemarket/client/cli/query.go
Small PR to migrate both modules CLI
----
Closes #XXX
> Ethermint migration of EVM and FeeMarket Cli 

- crypto/codec/amino.go
- crypto/codec/codec.go
- crypto/hd/algorithm.go
- crypto/hd/algorithm_test.go
- crypto/hd/benchmark_test.go
- encoding/codec/codec.go
- encoding/config.go
- encoding/config_test.go
- go.mod
- go.sum
Migrate files from Ethermint:
- missing files on the `crypto` pkg
- `encoding` pkg
----
Closes #XXX
> chore(migration) add crypto and encoding pkgs

- Makefile
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- proto/buf.gen.swagger.yaml
- scripts/protoc-swagger-gen.sh
This PR fixes the generation of Swagger files on the Evmos repository without permanently storing any third party proto files. Since using the remote plugins did not fully work as of yet (as described on the preceding PR evmos/evmos#1116 and in the Linear tickets [ENG-1042](https://linear.app/evmos/issue/ENG-1042) & [ENG-1093](https://linear.app/evmos/issue/ENG-1093)), I've opted for a solution to gather all relevant files in a temporary swagger-generation folder, download the deps on the fly and clean everything up afterwards.
It's necessary to create a designated Buf setup inside this isolated folder in order to enable using remote dependencies (defined in `buf.yaml`) for the generation of the Go types in the main repository (-> `make proto-gen`).
Other than the described changes, the …
> chore (proto): fix swagger generation and update swagger.yaml

- docs/developers/connect.md
> Update grpc port

- client/config.go
- client/config_test.go
- client/debug/debug.go
- client/export.go
- client/import.go
- client/keys.go
- client/keys/add.go
- client/keys/utils.go
- client/testnet.go
> chore(migration) add client pkg

- x/evm/genesis.go
- x/evm/genesis_test.go
- x/evm/handler.go
- x/evm/handler_test.go
- x/evm/module.go
- x/feemarket/genesis.go
- x/feemarket/handler.go
- x/feemarket/module.go
> chore(migration) add missing files on evm and feemarket modules

- app/ante/ante.go
> chore(migration) add Recover func to ante.go

- CHANGELOG.md
- go.mod
- go.sum
Minor Tendermint version bump
----
Closes #XXX
> chore (deps): bump Tendermint to `v0.34.25`

- docs/developers/connect.md
Added the BlockSpaces RPC endpoints to the list of mainnet providers
----
Closes #XXX
> Added BlockSpaces to RPC endpoint providers

- CHANGELOG.md
- x/evm/statedb/statedb.go
----
This PR exposes the `sdk.Context` for the `StateDB`
> imp(evm): StateDB Context

- CHANGELOG.md
- app/app.go
----
Updates the CHANGELOG with v11.0.1 changes
> chore: backport v11.0.1 changelog to main branch

- cmd/config/config.go
- server/start.go
- x/inflation/keeper/grpc_query_test.go
- x/inflation/keeper/inflation_test.go
- x/inflation/keeper/integration_test.go
Refactor inflation module tests to use `aevmos` as EVM denom
----
Closes https://linear.app/evmos/issue/ENG-1483/refactor-inflation-module-tests-to-use-basedenom-aevmos
> chore(tests) fix inflation keeper tests

- CHANGELOG.md
- app/forks.go
- app/upgrades/v11_1/constants.go
- x/erc20/types/msg.go
Hard fork logic for `v11.1.0` 
----
Closes #XXX
> fix(app): implement hard fork logic for v11.1.0

- CHANGELOG.md
- x/vesting/spec/01_concepts.md
- x/vesting/spec/05_antehandlers.md
Update docs with expected behavior
----
Closes https://linear.app/evmos/issue/ENG-1385/update-xvesting-documentation-with-expected-behavior
> chore(docs) update vesting docs

- CHANGELOG.md
Add changelog entry for PR #1349 
----
Closes #XXX
> chore(imp) add changelog entry for PR 1349

- CHANGELOG.md
- app/ante/cosmos/min_price_test.go
- app/ante/cosmos/utils_test.go
- app/ante/utils_test.go
- app/app_test.go
- app/test_helpers.go
- go.mod
- indexer/kv_indexer_test.go
- rpc/backend/backend_suite_test.go
- testutil/integration.go
- x/claims/genesis_test.go
- x/claims/keeper/ibc_callbacks_ibc_suite_test.go
- x/claims/keeper/integration_test.go
- x/claims/migrations/v3/types/params.go
- x/claims/types/params.go
- x/erc20/keeper/ibc_callbacks_integration_test.go
- x/erc20/keeper/ibc_callbacks_test.go
- x/erc20/keeper/integration_test.go
- x/evm/types/params.go
- x/ibc/transfer/keeper/keeper_test.go
- x/recovery/keeper/keeper_test.go
- x/revenue/keeper/integration_test.go
- x/revenue/keeper/keeper_test.go
- x/vesting/keeper/integration_test.go
Perform refactor to use `BaseDenom` instead of using `ClaimsDenom` and `EvmDenom` 
----
Closes https://linear.app/evmos/issue/ENG-1495/change-code-where-claimsdenom-and-evmdenom-is-used-for-basedenom
> chore(imp) refactor to use BaseDenom

- CHANGELOG.md
- app/ante/cosmos/vesting.go
- app/ante/evm/vesting.go
- app/ante/handler_options.go
- x/vesting/keeper/integration_test.go
After the Ethermint migration we eneded up organzing the decorator between evm specific decorators under the `evm` package and cosmos decorator under their  `cosmos` package. 
This PR makes the corresponding separation for the vesting decorators
----
Closes https://linear.app/evmos/issue/ENG-1501/split-vesting-decorators-between-evm-and-cosmos-packages
> chore(imp) split vesting decorators between evm and cosmos

- CHANGELOG.md
- app/ante/cosmos/min_price_test.go
- app/ante/cosmos/utils_test.go
- app/ante/evm/eth_test.go
- app/ante/evm/fee_market_test.go
- app/ante/evm/fees_test.go
- app/ante/evm/setup_ctx_test.go
- app/ante/evm/signverify_test.go
- app/ante/evm/utils_test.go
- app/ante/evm/vesting_test.go
- testutil/ante.go
- testutil/tx/cosmos.go
This PR moves the `invalidTx` type and `NextFn` used in AnteHandler tests to the testutil package.
> imp(tests): refactor some AnteHandler test utilities to the testutil package

- testutil/setup.go
- x/claims/keeper/utils_test.go
- x/epochs/keeper/utils_test.go
- x/erc20/keeper/utils_test.go
- x/evm/keeper/setup_test.go
- x/feemarket/keeper/utils_test.go
- x/ibc/transfer/keeper/keeper_test.go
- x/incentives/keeper/utils_test.go
- x/inflation/keeper/utils_test.go
- x/recovery/keeper/setup_test.go
- x/revenue/keeper/utils_test.go
- x/vesting/keeper/utils_test.go
> tests: header testutil

- app/ante/cosmos/authz_test.go
- app/ante/evm/utils_test.go
- testutil/abci.go
- testutil/tx/cosmos.go
- testutil/tx/eip712.go
Renamed CosmosTxInput to CosmosTxArgs to be consistent with a similar existent struct (`EvmTxArgs`)
----
Closes #XXX
> chore(tests) rename CosmosTxInput to CosmosTxArgs

- tests/e2e/e2e_test.go
Update e2e test with expected error message
----
Closes #XXX
> chore(tests) update e2e test

- app/ante/cosmos/authz_test.go
- app/ante/cosmos/utils_test.go
This is a small housekeeping PR, that removes an unnecessary mocked AnteHandler interface and replaces its use with a utility from the `testutil` package.
> chore (ante): remove unnecessary mocked ante handler from tests

- types/account.go
> chore(types): fix typo from porting

- go.mod
- go.sum
- server/flags/flags.go
----
Closes https://linear.app/evmos/issue/ENG-1561/bump-cosmos-sdk-version-to-include-new-fees-flag
> chore(deps) bump cosmos-sdk version to v0.46.11-ledger

- README.md
This PR includes the following adjustments in `README.md`:
----
Closes ENG-1575
> chore: fix outdated codecov badge in README

- README.md
- go.mod
> chore: bump go version to 1.20

- CHANGELOG.md
- x/evm/keeper/state_transition.go
Consider the refund for updating the leftover gas and gas used.
This change does not have an effect on current implementation because refund amount is zero
----
Closes #XXX
> chore(gas) consider refund for gasUsed

- go.mod
- go.sum
----
Update Evmos-Ledger-Go dependency to new release to fix runtime issues.
> fix: bump evmos-ledger-go version

- CHANGELOG.md
- app/upgrades/v12/constants.go
- tests/e2e/upgrade/utils_test.go
This PR adjust the changelog and upgrade constants for the release of `v12.0.0-rc1`.
> release: v12.0.0-rc1

- tests/e2e/upgrade/utils_test.go
This PR pushes a small fix to allow upgrade versions to include the release candidate appendix (e.g. `-rc1`) in the unit tests for the upgrade test utilities.
> fix (tests): fix version assertion to be valid for release candidates

- CHANGELOG.md
- rpc/backend/tx_info.go
- rpc/backend/tx_info_test.go
----
Closes https://github.com/evmos/evmos/issues/1462
> fix(evm): add gas used

- .github/workflows/build.yml
- .github/workflows/dependencies.yml
- .github/workflows/goreleaser.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/upgrade-test-release.yml
- .github/workflows/upgrade-test.yml
After updating the CI workflows to use Go v1.20 (#1469), the actions did not run properly as they built v1.2.2. This is fixed by specifying the Go version as a string.
See this issue for reference: https://github.com/actions/setup-go/issues/326#issuecomment-1415719692
> fix (ci): fix used Go version in CI by passing version as a string

- .github/workflows/codeql-analysis.yml
After moving our docs to their dedicated repo at [evmos/docs](https://github.com/evmos/docs) there are no Python files left in the repository. This caused the CodeQL action to fail since it was looking for Python code to scan.
> chore (ci): remove python from CodeQL action

- CHANGELOG.md
- go.mod
- go.sum
> deps: update cosmos-sdk version

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependencies.yml
- .github/workflows/goreleaser.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .github/workflows/upgrade-test-release.yml
- .github/workflows/upgrade-test.yml
- .golangci.yml
- CHANGELOG.md
- app/ante/cosmos/min_price.go
- app/ante/cosmos/min_price_test.go
- app/ante/evm/fee_checker.go
- app/ante/evm/fee_checker_test.go
- app/ante/evm/fees.go
- app/ante/handler_options.go
- app/ante/handler_options_test.go
- app/upgrades/v12/constants.go
- go.mod
- go.sum
- networks/local/evmos/Dockerfile
- rpc/backend/tx_info.go
- rpc/backend/tx_info_test.go
- server/flags/flags.go
- tests/e2e/e2e_test.go
This PR pulls the latest changes from `main` and updates the changelog and constants for the v12.0.0-rc2 release.
> chore: release v12.0.0-rc2

- CHANGELOG.md
> release: update changelog for v12-rc3

- CHANGELOG.md
> fix: changelog for v12-rc3 release

- CHANGELOG.md
- app/upgrades/v12/constants.go
> chore: update upgrade constants and changelog

- app/ante/cosmos/fees_benchmark_test.go
- app/ante/cosmos/fees_test.go
- app/ante/cosmos/utils_test.go
> imp: add new benchmark tests for ante handler

- CHANGELOG.md
- app/app.go
- app/upgrades/v12/constants.go
This PR merges the v12 release branch back into the main branch on Evmos.
> chore: merge v12 release branch back into main

- CHANGELOG.md
> chore: update changelog for v12.1.1

- CHANGELOG.md
> chore: update changelog with v12.1.1 release and missing entry for #1431

- CHANGELOG.md
- rpc/websockets.go
> chore: backport "fix: parse for websocket connID" (#1431)

- CHANGELOG.md
> chore: update changelog with v12.1.2

- testutil/contract.go
- testutil/staking-rewards.go
----
Closes https://linear.app/evmos/issue/ENG-1733/add-new-functions-to-evmos-testutil
> chore: add new testutil functions: call contract and create validator

- app/app.go
- app/upgrades/v13/upgrades.go
> chore: add precompile params init (to release)

- .github/workflows/bsr-push.yml
This PR fixes the GitHub action to push the Protobuf implementation to the Buf Schema Registry. Apparently, it didn't recognize the `with: buf_token=...` syntax.
> fix (ci): fix bsr push action

- CHANGELOG.md
- go.mod
- go.sum
> deps: bump sdk version to v0.46.10-ledger.3 (release/v12.x.x)

- CHANGELOG.md
- go.mod
- go.sum
> deps: bump sdk version to v0.46.11-alpha.ledger.7

- CHANGELOG.md
- app/upgrades/v12/constants.go
This PR prepares the release of `v12.1.3` by adjusting the changelog and upgrade constants accordingly.
> chore: release v12.1.3

- CHANGELOG.md
> chore: update changelog w/ v12.1.3

- CHANGELOG.md
- go.mod
- go.sum
> deps: bump ibc-go version

- CHANGELOG.md
This PR adjusts the changelog for the release of `v12.1.4`.
> chore: prepare release of v12.1.4

- CHANGELOG.md
This PR updates the changelog to include the release info for `v12.1.4`.
> chore: update changelog with v12.1.4

- go.mod
- go.sum
> chore(deps): bump ibc-go version to v6.2.0

- CHANGELOG.md
- x/vesting/keeper/integration_test.go
Update changelog for v12.1.5
----
Closes #XXX
> Update Changelog for v12.1.5

- app/upgrades/v13/constants.go
> fix(upgrade): update release candidate name and binaries

- CHANGELOG.md
> Upstream changelog changes from v13.0.0-rc2

- CHANGELOG.md
- go.mod
- go.sum
- ibc/module_test.go
- x/erc20/types/erc20.pb.go
- x/vesting/keeper/integration_test.go
- x/vesting/types/msg.go
Update precompiles repo version to include fix hard coded BaseDenom issue.
----
Closes #XXX
> fix: Fixed the BaseDenom and wrong comparison for MaxUint256

- .github/workflows/lint.yml
- CHANGELOG.md
- LICENSE_FAQ.md
- go.mod
- go.sum
- ibc/module_test.go
- x/erc20/types/erc20.pb.go
- x/vesting/keeper/integration_test.go
- x/vesting/types/msg.go
Sync branch release/v13.0.x with main. It includes [this](https://github.com/evmos/precompiles/pull/160) to fix main issue with precompiles in testnet.
----
Closes #XXX
> Release v13.0.0-rc3

- app/upgrades/v13/constants.go
> Set upgrade constants for v13.0.0-rc3 release

- cmd/evmosd/root.go
----
i was unable to test this because of the private repo stuff.
> add snapshot cmds

- x/erc20/keeper/ibc_callbacks_integration_test.go
> tests: add timeout packet case for registered erc20

- server/config/config.go
This PR adjusts the default app configuration to disable all options (as opposed to just the API). Desired options need to be manually set by node operators
> chore(server): adjust default app configuration to disable all server options

- CHANGELOG.md
Recently, we've merged a bunch of PRs without appropriate changelog entries. Additionally, I've adjusted an existing entry for v13.0.0-rc3 to point to the corresponding PR on Evmos instead of the precompiles repo.
> chore(changelog): add missing changelog entries

- CHANGELOG.md
This PR merges the changelog updates from v12.1.5 back to `main`.
> chore: update changelog with v12.1.5

- CHANGELOG.md
- app/upgrades/v13/constants.go
This PR updates the Changelog and upgrade constants for the v13.0.0 release.
> chore(release): prepare v13.0.0

- CHANGELOG.md
- go.mod
- go.sum
----
Closes https://github.com/evmos/evmos/issues/1629, for more [info](https://github.com/cometbft/cometbft/blob/v0.34.29/CHANGELOG.md#v03429)
> Problem: cometbft dependency is not updated

- CHANGELOG.md
This PR adjusts the changelog in preparation of the v12.1.6 patch release.
> chore(release): prepare v12.1.6 changelog

- CHANGELOG.md
This PR updates the changelog for v13.0.1, a patch release to update the CometBFT dependency.
> chore(release): update changelog for v13.0.1

- tests/e2e/e2e_suite_test.go
- tests/e2e/e2e_test.go
- tests/e2e/upgrade/node.go
for available tags, see https://hub.docker.com/r/tharsishq/evmos/tags
----
Closes #XXX
> fix(test): add version map and home flag for upgrade

- .github/workflows/bsr-push.yml
This PR points the GH action to push the Protobuf files to the Buf Schema Registry to the corresponding subfolder. Previously, the action failed since `buf.yaml` wasn't found on the root level (see [here](https://github.com/evmos/evmos/actions/runs/5455571831/jobs/9927206951)).
> chore(ci): point proto push action to subfolder

- .github/CODEOWNERS
- .github/workflows/bsr-push.yml
- .github/workflows/proto.yml
- CHANGELOG.md
- app/upgrades/v13/constants.go
- tests/e2e/e2e_suite_test.go
- tests/e2e/e2e_test.go
- tests/e2e/upgrade/node.go
This PR prepares the release of `v13.0.2` - a necessary patch release to update the upgrade constants in order for a coordinated software upgrade to be possible for mainnet.
After merging `main` to the release branch fixes for the GH action to push to the Buf Schema Registry as well as a fix for the E2E tests are included.
> chore(upgrade): prepare v13.0.2

- precompiles/ics20/ICS20.sol
Add the `view` modifier on the query methods
----
Closes #XXX
> chore(precompiles): update IBC transfer interface

- CHANGELOG.md
- Makefile
- rpc/ethereum/pubsub/pubsub.go
- rpc/ethereum/pubsub/pubsub_test.go
This PR introduces the changes to solve reported racing conditions on the RPC pubSub logic
Reported issue logs:
```
fatal error: concurrent map iteration and map write
goroutine 12880390 [running]:
github.com/evmos/evmos/v12/rpc/ethereum/pubsub.(*memEventBus).publishAllSubscribers(0xc106c0b500, {0xc000fdab80?, 0xe53d86?}, {{0xc4b4d0baa0, 0x19}, {0x2987720, 0xc2bdef9880}, 0xc4b714af30})
/go/src/github.com/tharsis/evmos/rpc/ethereum/pubsub/pubsub.go:152 +0x16f
github.com/evmos/evmos/v12/rpc/ethereum/pubsub.(*memEventBus).publishTopic(0xc106c0b500, {0xc000fdab80, 0x19}, 0xc1051f8bd0?)
...
```
----
Closes #XXX
> fix(rpc): concurrent map iteration and write

- .github/workflows/e2e-test-release.yml
This PR removes the outdated `if: env.GIT_DIFF` instruction from the e2e release test workflow. This was a remainder from when we checked for individual changed files before switching to running the E2E tests on every PR to a release branch.
> chore(ci): remove outdated if env.GIT_DIFF from e2e release workflow

- CHANGELOG.md
- server/config/config.go
- server/start.go
Updated defaults on CLI flags based on changes introduced on PR https://github.com/evmos/evmos/pull/1623/
----
Closes #XXX
> chore(cli): update defaults based on latest changes

- CHANGELOG.md
- rpc/namespaces/ethereum/eth/filters/filter_system.go
- rpc/namespaces/ethereum/eth/filters/filter_system_test.go
----
for more [info](https://github.com/evmos/ethermint/issues/1745)
> fix: avoid channel get changed when concurrent subscribe happens

- CHANGELOG.md
- app/app.go
- precompiles/testutil/contracts/contracts.go
- testutil/abci.go
- testutil/contract.go
- x/revenue/v1/keeper/evm_hooks.go
Avoid running TxPostProcessing hook when developers shares are set to 0
----
Closes #XXX
> fix: check if developers shares are set to 0

- CHANGELOG.md
- app/upgrades/v14/constants.go
This PR updates the changelog and upgrade constants for the v14.0.0-rc1 release.
> chore: prepare v14.0.0-rc1 release

- CHANGELOG.md
- tests/e2e/init-node.sh
- tests/e2e/upgrade/Dockerfile.init
This PR adjusts the Dockerfile and initialization script for the end-to-end tests, as they are currently failing.
----
Closes ENG-1950
> fix(tests): fix Dockerfile and init script for e2e tests

- CHANGELOG.md
- x/vesting/client/cli/tx.go
----
This PR aims to update docs for cli cmd `fund-vesting-account`
> docs: update vesting v2 cli

- CHANGELOG.md
- server/util.go
Add the missing command needed to bootstrap the state when restoring a snapshot locally
----
Closes #XXX
> chore: add bootstrap state command

- CHANGELOG.md
> chore: adjust changelog

- CHANGELOG.md
- app/ante/evm/fees.go
- app/ante/evm/fees_test.go
> fix panic bug "Int64() out of bound" in ante handler

- CHANGELOG.md
- cmd/evmosd/root.go
- go.mod
- go.sum
- server/config/config.go
> chore: update gas adjustment factor

- CHANGELOG.md
- x/evm/keeper/state_transition.go
- x/evm/keeper/state_transition_test.go
> fix panic on uint64 conversion in evm ApplyMessageWithConfig function

- local_node.sh
This reenables the metrics on the local node, which was accidentally removed in #1715.
> fix(tests): reenable metrics on local node

- precompiles/ics20/events.go
- rpc/backend/blocks_test.go
- rpc/types/events_test.go
This PR fixes some linter issues that occured after bumping the `golangci-lint` version recently. This was fixed on the release/v14.0.x branch already, now applying here too.
> chore(lint): fix linter

- CHANGELOG.md
- precompiles/vesting/integration_test.go
- precompiles/vesting/query.go
- precompiles/vesting/query_test.go
- precompiles/vesting/tx.go
- precompiles/vesting/tx_test.go
- precompiles/vesting/vesting.go
- x/claims/migrations/v3/types/genesis.pb.go
- x/erc20/migrations/v3/types/genesis.pb.go
- x/revenue/v1/migrations/v2/types/genesis.pb.go
- x/vesting/keeper/msg_server.go
This PR removes the ability to create a `ClawbackVestingAccount` for smart contract address by checking the `CodeHash` on the `CreateClawbackVestingAccount` transaction
----
Closes ENG-2001
> fix(vesting): remove smart contract conversion to ClawbackVestingAccount

- CHANGELOG.md
- go.mod
- go.sum
Update IBC dependency to include the fix for the UTC timezone in packet timeout error message
----
Closes #XXX
> chore(deps) bump ibc

- CHANGELOG.md
- app/ante/cosmos/fees.go
- app/app.go
- x/vesting/keeper/gov.go
- x/vesting/keeper/hooks.go
- x/vesting/keeper/integration_test.go
- x/vesting/keeper/keeper.go
- x/vesting/keeper/keeper_test.go
- x/vesting/keeper/msg_server.go
- x/vesting/keeper/utils_test.go
- x/vesting/types/interfaces.go
- x/vesting/types/keys.go
> imp(vesting): module refactors

- x/vesting/keeper/msg_server.go
Some minor cleanups regarding #1754.
> chore(vesting): add some nit fixes

- .github/workflows/e2e-test.yml
- Dockerfile
Currently, the docker image throws this error when building:
```
1.054 ERROR: unable to select packages:
1.055   rclone-1.62.2-r4:
1.055     breaks: world[rclone=1.62.2-r3]
```
This PR adds the fix for this
----
Closes #XXX
> chore(docker): update rclone dep version

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependencies.yml
- .github/workflows/e2e-test-release.yml
- .github/workflows/e2e-test.yml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .github/workflows/semgrep.yml
- .github/workflows/solidity-test.yml
- .github/workflows/test.yml
> chore: edit gh flow to rerun actions when gomod2nix.toml is updated programmatically

- x/vesting/keeper/gov.go
Just savin' some bytes here.
----
Closes #XXX
> imp(vesting): store empty byte array instead of "true" bytes

- CHANGELOG.md
- app/upgrades/v14rc5/upgrades.go
- app/upgrades/v14rc5/upgrades_test.go
This PR adjusts the changelog to have today's date as the release date for v14.0.0-rc5. Additionally, after some considerations we decided to disable the distribution extension on testnet in order to test calls to an inactive EVM extension.
To follow best practices, the upgrade logic is also covered with tests.
> chore(release): adjust changelog + disable distribution extension on upgrade

- Dockerfile
> chore: update docker dep

- CHANGELOG.md
- app/app.go
This PR removes the migration logic from the app's `BeginBlocker`.
----
Closes ENG-2167
> remove migration logic from the begin blocker

- CHANGELOG.md
- go.mod
- go.sum
- gomod2nix.toml
Closing https://github.com/evmos/evmos/pull/1749 in favor of this one cause contributor is not responsive 
----
Closes ENG-2140
> chore(deps): Use IAVL v0.20.1 & Fix Concurrency issue on mainnet

- app/app.go
- app/upgrades/v14_2/constants.go
- app/upgrades/v14_2/upgrades.go
This PR adds the basic upgrade logic for the v14.2.0 release. The necessary migration logic is added on a separate PR.
----
Closes ENG-2152
> chore(upgrade): add basic logic to prepare for v14.2 upgrade

- CHANGELOG.md
- app/app.go
- app/upgrades/v14_2/upgrades.go
This PR adds the necessary account migration to the release branch in preparation of v14.2.0.
----
Closes ENG-2168
> chore(upgrade): add migration to upgrade logic

- CHANGELOG.md
- app/app.go
- app/upgrades/v14_2/upgrades.go
For this PR the changes from #1845 have been cherry-picked to the `main` branch. The normal backport flow didn't work because there was a previous backport created which was messed up (#1853).
> chore(upgrade): add migration to upgrade logic (backport #1845)

- client/docs/swagger-ui/swagger.json
This PR removes the hardcoded BlockDaemon server from the Swagger JSON file. This value is populated by the @evmos/devops team when deploying the Swagger API pages.
> chore(swagger): remove bd from swagger config

- Dockerfile
This PR updates the used `rclone` version in the Dockerfile to enable building Docker images again. This will also fix the E2E tests.
> chore(build): update rclone version in Dockerfile

- local_node.sh
> fix: remove unnecessary edit in local node script

- tests/nix_tests/test_no_abci_resp.py
> fix(test): use different port to avoid collision

- tests/e2e/init-node.sh
> chore(tests) update init script to set memIAVL disabled as default

- CHANGELOG.md
- server/config/config.go
- tests/nix_tests/hardhat/package-lock.json
> chore: add default memIAVL config

- app/upgrades/v15rc1/constants.go
> chore: update bins for v15.0.0-rc1 release

- CHANGELOG.md
- app/upgrades/v15/utils_test.go
- x/evm/keeper/grpc_query_test.go
- x/evm/migrations/v4/migrate_test.go
- x/evm/types/params.go
> chore(evm): enable EIP 3855 by default

- testutil/integration/grpc/grpc.go
- testutil/integration/grpc/staking.go
- testutil/integration/network/clients.go
- testutil/integration/network/network.go
- x/evm/keeper/integration_test.go
----
Closes #XXX
CacheContext should be use on grpc client instead so that undesired state is not commited during integration tests.
> fix: use CacheContext on integration tests grpc clients

- CHANGELOG.md
> chore(changelog): Fix Changelog

- .github/workflows/auto-format.yml
- app/app.go
Add auto formatting for golang files
----
Closes ENG-2176
> chore(ci): add auto formatting

- precompiles/outposts/stride/IStrideOutpost.sol
- precompiles/outposts/stride/abi.json
> feat(stride): Stride Outpost interface and abi.

- CHANGELOG.md
- precompiles/ics20/events.go
- precompiles/ics20/tx.go
This is needed to no repeat the same Event emitting logic in each of the Outposts. Also adding all forgotten changelog entries from previous PRs.
----
Closes #XXX
> fix(ics20): Make event emitting a common function

- CHANGELOG.md
- precompiles/ics20/types.go
- precompiles/outposts/stride/stride.go
This PR:
-  adds the DefaultTimeoutHeight as a constant value in the precompile ics20 package.
- substitute the hardcode value of timeout height in Stride outpost with the default value.
----
Closes #XXX
> chore(ics20): timeout height as const

- precompiles/p256/p256.go
- precompiles/p256/p256_test.go
> imp: address comments from review

- precompiles/erc20/IERC20.sol
- precompiles/erc20/IERC20Metadata.sol
- precompiles/erc20/IERC20MetadataAllowance.sol
- precompiles/erc20/abi.json
- precompiles/werc20/IWERC20.sol
- precompiles/werc20/abi.json
----
Adds the ABI and Solidity interfaces for both ERC20 and WERC20 precompiles
> feat(erc20): ERC20 Solidity interface and ABI

- precompiles/bank/IBank.sol
- precompiles/bank/abi.json
----
Defines the Solidity Interface and ABI for the Bank Precompile
> feat(precompiles): Bank Solidity Interface and ABi

- testutil/integration/network/network.go
> imp(testutil): expose App to Network

- tests/nix_tests/test_osmosis_outpost.py
- tests/nix_tests/test_patches.py
- tests/nix_tests/test_precompiles.py
- tests/nix_tests/test_stride_outpost.py
This PR adds the test to cover the case reported in https://github.com/evmos/evmos/pull/1801
----
Closes #XXX
> chore(tests) add distr mod eth transfer test

- testutil/integration/network/network.go
- testutil/integration/network/unit_network.go
Instead of making the app public on the Integration Network interface we can make an specific struct for UnitTesting that makes this variable public and satisfies the same struct. This keeps our integration network setup clean and enforces the privacy of the App and Context through those tests. This new struct could also be expanded with common needs the unit tests might have as we start refractoring them.
Alternative is to create a new `Network` Interface instead of just the struct - e.g `UnitTestNetwork` with an `GetApp` method. But thought this was simpler since it does not make much sense to have methods that returns pointers to private fields. 
----
Closes #XXX
> imp(testutil): Add UnitTestNetwork struct for unit testing setup

- x/erc20/keeper/token_pairs.go
- x/erc20/keeper/token_pairs_test.go
This PR add to the ERC20 keeper a method to get a token denom given a token address and relative tests.
> imp(erc20): add GetTokenDenom method to keeper

- x/evm/types/params.go
Remove bank precompile address from `evm` params until it's fully implemented
----
Closes #XXX
> fix: remove bank address from params

- CHANGELOG.md
This PR prepares the changelog for the v15.0.0-rc2 release.
> chore(upgrade): update changelog for v15.0.0-rc2

- x/evm/keeper/grpc_query_test.go
The stride outpost setup included in https://github.com/evmos/evmos/pull/1958 makes the expected gas in the TraceTx and traceBlock increase. This PR updates those values to fix the failing tests
----
Closes #XXX
> fix(test): update exp gas

- CHANGELOG.md
- app/app.go
> chore(gov): remove deprecated param change proposal handler

- precompiles/erc20/events.go
> imp(erc20): ERC-20 Events

- .github/workflows/changelog.yml
- CHANGELOG.md
This PR adds a CI action to check if there has been a Changelog entry added for any PR to `main`.
> imp(ci): add changelog diff check to ci

- CHANGELOG.md
- precompiles/werc20/tx.go
> feat(werc20): WERC20 transactions

- CHANGELOG.md
- precompiles/werc20/events.go
- precompiles/werc20/tx.go
- precompiles/werc20/types.go
> imp(werc20): WERC-20 Events

- precompiles/erc20/erc20.go
- precompiles/werc20/werc20.go
> imp(erc20): uncomment precompile methods in Run

- .github/workflows/changelog.yml
This PR change the name of the changelog workflow single job
----
Closes #XXX
> chore: change: change changelog workflow job name

- CHANGELOG.md
- precompiles/outposts/osmosis/IOsmosisOutpost.sol
- precompiles/outposts/osmosis/abi.json
This PR update the Osmosis outpost ABI including the next sequence to the Swap function return.
----
Closes #XXX
> chore: update osmosis outpost abi

- CHANGELOG.md
- utils/utils.go
This PR adds a function to the `utils/utils` package for creating the denomination trace of an IBC token. This function simplifies the code when you need to create an IBC denom trace.
----
Closes #XXX
> chore: ibc denom trace function

- CHANGELOG.md
- precompiles/outposts/osmosis/errors.go
- precompiles/outposts/osmosis/osmosis.go
- precompiles/outposts/osmosis/setup_test.go
- precompiles/outposts/osmosis/tx.go
- precompiles/outposts/osmosis/types.go
- precompiles/outposts/osmosis/types_test.go
This is just a small cleanup PR as discussed with @0xstepit yesterday. His original PR https://github.com/evmos/evmos/pull/1986 will include the changes to the `swap` transaction and the inclusion of the XCS contract address in function params.
----
Closes #XXX
> fix(osmosis): Refactor types, errors and precompile constructor

- CHANGELOG.md
- precompiles/outposts/osmosis/types_test.go
- precompiles/outposts/osmosis/utils_test.go
This PR add utils test function to check that the outpost memo is correctly parsed from the Osmosis' Wasm Hook. Because of the many dependencies in the Osmosis package, the function are here reimplemented and adapted to our use case instead of importing them. Please feel free to suggest another approach if you think something more optimized can be done.
----
Closes ENG-2317
> chore(outpost): add osmosis wasm hook validation

- CHANGELOG.md
- precompiles/bank/query_test.go
> tests(bank): supplyOf query unit tests

- x/evm/keeper/grpc_query_test.go
This PR update the gas consuption in an evm query test.
----
Closes ENG-2322
> test(evm): update test gas consumption

- CHANGELOG.md
- precompiles/werc20/integration_test.go
- precompiles/werc20/werc20.go
----
This PR adds comparison integration tests with the original `WEVMOS9` contract by deploying it and executing the same transactions. 
Closes #XXX
> tests(werc20): Add WEVMOS acceptance tests

- precompiles/erc20/tx_test.go
This PR updates the existing unit tests for the `transferFrom` method, because they have been relying on the case where the owner is the spender. This should only be an edge case IMO, and I've adjusted this accordingly.
> tests(erc20): adjust transfer from unit tests to not rely on own account spending

- CHANGELOG.md
- precompiles/p256/p256.go
- x/evm/types/params.go
This PR adjusts the p256 precompile address to 0x0b as described on this PR: https://github.com/ethereum/EIPs/pull/7970.
----
Closes ENG-2364
> chore(p256): adjust p256 precompile address

- CHANGELOG.md
- app/ante/ante.go
- app/ante/cosmos/authz_test.go
- app/ante/evm.go
- app/ante/evm/setup_test.go
- app/ante/evm/utils_test.go
- testutil/tx/eip712.go
This PR reverts the deprecation of the EIP-712 ante handler for the `v16.0.0-rc1` release.
----
Closes ENG-2361
> revert deprecation of EIP-712 ante handler for v16.0.0-rc1

- CHANGELOG.md
- app/upgrades/v16/upgrades.go
This PR enables the stride and osmosis outposts during the v16 upgrade.
----
Closes ENG-2365
> feat(stride,osmosis): enable stride and osmosis outposts during upgrade

- CHANGELOG.md
- app/upgrades/v16/upgrades.go
> chore(upgrade): Activate bech32 precompile during upgrade

- CHANGELOG.md
- app/upgrades/v16/upgrades.go
> chore(bech32): Activate bech32 precompile

- CHANGELOG.md
- app/app.go
- app/upgrades/v16/upgrades.go
After discussion with validators we are adjusting the upgrade handler to remove the call to the method which is burning the incentives pool.
> fix(incentives): remove incentives burning logic from upgrade handler

- CHANGELOG.md
- app/upgrades/v16/constants.go
This PR prepares the release branch for the v16.0.0-rc1 release.
> chore(upgrade): Prepare v16.0.0-rc1

- Dockerfile
This PR updates the dependencies of `jq` and `curl` in the Dockerfile.
> imp(docker): update jq and curl dependencies

- gomod2nix.toml
> chore: update gomod2nix

- app/ante/evm/04_validate.go
- app/ante/evm/04_validate_test.go
- app/ante/evm/09_gas_consume.go
- app/ante/evm/ante_test.go
- app/ante/evm/mono.go
> imp(ante): ValidateMsg refractor and remove legacy decorator

- app/app.go
- app/upgrades/v16/upgrades.go
> fix(upgrade): Add upgrade handler for rc2

- tests/nix_tests/cosmoscli.py
- tests/nix_tests/test_filters.py
- tests/solidity/suites/basic/test/storage.js
- tests/solidity/suites/opcode/contracts/OpCodes.sol
fix typos
I have...
[type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json)
in the PR title
(see [PR Targeting](https://github.com/evmos/evmos/blob/main/CONTRIBUTING.md#pr-targeting))
I have...
______
I have...
[type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json)
in the PR title
> chore(tests): fix typos

- Dockerfile
> chore(docker) update deps

- app/ante/cosmos/min_price.go
- precompiles/ics20/integration_test.go
- precompiles/ics20/utils_test.go
- proto/ethermint/evm/v1/tx.proto
- rpc/backend/node_info.go
- rpc/types/events.go
- x/erc20/keeper/integration_test.go
- x/evm/types/tx.pb.go
----
fix some typos accross muti file
> chore(rpc,proto,app,evm,erc20):fix typos

- app/ante/evm/10_incremenet_sequence_test.go
- app/ante/evm/11_gas_wanted_test.go
- testutil/integration/evmos/grpc/feemarket.go
- testutil/integration/evmos/grpc/grpc.go
- testutil/integration/evmos/network/network.go
- testutil/integration/evmos/network/params.go
> imp(ante): Remove legacy GasWanted decorator and refractor tests

- CHANGELOG.md
- app/upgrades/v16/upgrades.go
This PR uncomments the burning of the usage incentives pool balance in light of [proposal 262](https://mintscan.io/evmos/proposals/262) passing.
> chore(upgrade): enable burning the usage incentives pool in the v16 handler

- CHANGELOG.md
- app/app.go
- app/forks.go
- app/upgrades/v16/constants.go
- app/upgrades/v16/upgrades.go
This PR combines all individual rc upgrade handlers for v16 into one. Additionally, outdated upgrade constants are removed and the hard fork logic is commented out, as it is not required anymore.
----
Closes ENG-2452
> chore(upgrade): combine v16 upgrade handlers

- precompiles/staking/types.go
Fix the problem of the error message of the NewMsgCreateValidator function return the wrong message. This is a very low-level problem that occurs after using copy.
> fix(staking): fix NewMsgCreateValidator return err info is wrong

- CHANGELOG.md
This PR prepares the changelog for v16.0.0.
----
Closes ENG-2454
> chore(changelog): Prepare changelog for v16.0.0

- CHANGELOG.md
This PR adds the missing changelog entry for #2234.
> fix(changelog): add missing changelog entry for #2234

- CHANGELOG.md
- app/post/burn.go
- app/post/burn_test.go
> chore: add burnt coins metrics

- CHANGELOG.md
This PR adjusts the changelog for the v16.0.1 patch release.
> chore(upgrade): Prepare changelog for v16.0.1

- .github/labeler.yml
- CHANGELOG.md
This PR fixes the pull request labeler workflow by updating the configuration file after the expected format was changed between versions 4 and 5.
The new proposed labels are:
- `proto`
- `types`
- `build`
- `CI`
- `CLI`
- `tests`
- `contracts` for changes to any Solidity contracts or files in the contracts directory
- `release` for pull requests to the release branches
- `feature` for feature branches
- `precompile` for any changes in the precompiles directory
----
Closes ENG-2451
> fix(ci): Update configuration for pull request labeler

- .github/workflows/ante-benchmark.yml
- .github/workflows/auto-format.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-test.yml
- .github/workflows/labeler.yml
- .github/workflows/lint.yml
- .github/workflows/markdown-links.yml
- .github/workflows/security.yml
- .github/workflows/semgrep.yml
- .github/workflows/slither.yml
- .github/workflows/solhint.yml
- .github/workflows/super-linter.yml
- CHANGELOG.md
This PR fixes the configuration of some CI actions we have that are not running when there is no appropriate diff in the PRs. The new required items _always_ require the CI to run, so we stop it using the git diff action.
Additionally, the CI items are not run on pushes to `main` anymore, because we **never** push to it without a PR, where those CI items are run already. In that sense, we've had a lot of duplicate runs up to this point.
> fix(ci): fix CI config for required items to always run but stop when no diff

- codecov.yml
This PR adjusts the Codecov configuration in order to require a 90% diff hit across the board.
We are for now removing the individual configuration of the per-folder basis. If necessary we can add it again.
> chore(ci): adjust codecov settings to require 90% diff hit across the board

- .github/labeler.yml
- CHANGELOG.md
- precompiles/p256/p256_test.go
This PR takes the changes made by @anshalshukla in #2262 and wraps the test execution in a `Run(...)` call to be aligned with other tests in the repo and have a better output in IDEs.
> imp(tests): Minor clean up in EIP-7212 tests

- CHANGELOG.md
- x/inflation/v1/keeper/genesis_test.go
- x/inflation/v1/keeper/grpc_query_test.go
- x/inflation/v1/keeper/hooks.go
- x/inflation/v1/keeper/hooks_test.go
- x/inflation/v1/keeper/inflation.go
- x/inflation/v1/keeper/inflation_test.go
- x/inflation/v1/keeper/integration_test.go
This PR:
- updates the inflation query to return the correct value
- update tests
This fix is a quick fix to release a patch for the query, not the best approach. In a future PR the reduction factor of the inflation, now 1/3, will be moved in the Params and the  [CalculateEpochMintProvision](https://github.com/evmos/evmos/blob/6304c281fd297fde68ebd5e646c46948b708605f/x/inflation/v1/types/inflation_calculation.go#L13-L13) will be updated to use it.
Closes ENG-2457
> fix(inflation): update query to return correct inflation value

- CHANGELOG.md
- testutil/integration/common/grpc/bank.go
- testutil/integration/evmos/grpc/grpc.go
- testutil/integration/evmos/network/config.go
- testutil/integration/evmos/network/config_test.go
- testutil/integration/evmos/network/network.go
- testutil/integration/evmos/network/setup.go
This PR is a follow-up to #2167 which enables specifying the pre-funded balances when setting up the integration test suite.
To do this, pass `WithBalances(...)` instead of `WithPreFundedAccounts(...)` into the creation of the network instance.
**Note:** `WithBalances` is preferred over `WithPreFundedAccounts` so should you pass both only the predefined balances are taken into account.
> imp(tests): Enable specifying the prefunded balances for the integration test setup

- app/app.go
- app/upgrades/v17/constants.go
- app/upgrades/v17/upgrades.go
This PR adds the generic v17 upgrade handler.
> chore(upgrade): Add v17 handler

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> chore(changelog): Prepare changelog for v16.0.3

- x/evm/keeper/abci_test.go
- x/evm/keeper/statedb_test.go
Closes: #XXXX
Small PR to fix the last two failing tests of the EVM Keeper
---
I have...
I have...
> fix(tests): Fix statedb and abci tests on the EVM module

- x/evm/genesis_test.go
- x/evm/handler_test.go
This PR only addresses the tests on the `handler_test.go` and `genesis_test.go` files.
The changes comprise the needed refactoring to make the test work with the sdk v0.50.
With these changes, all tests on the `x/evm` module are passing
```
❯ go clean --testcache &&  go test ./...
?       github.com/evmos/evmos/v16/x/evm/migrations/v4/types    [no test files]
?       github.com/evmos/evmos/v16/x/evm/migrations/v5/types    [no test files]
?       github.com/evmos/evmos/v16/x/evm/migrations/v6/types    [no test files]
ok      github.com/evmos/evmos/v16/x/evm        2.127s
ok      github.com/evmos/evmos/v16/x/evm/client/cli     0.156s
ok      github.com/evmos/evmos/v16/x/evm/keeper 8.599s
ok      github.com/evmos/evmos/v16/x/evm/migrations/v4  0.156s
ok …
```
> fix(tests): refactor genesis and handler tests for sdk v0.50

- CHANGELOG.md
- testutil/integration/evmos/factory/broadcast.go
- testutil/integration/evmos/factory/build.go
- testutil/integration/evmos/factory/factory.go
Closes: #XXXX
Upstreaming some factory functions from the sdk50 branch that are starting to be useful on other tests. 
---
I have...
I have...
> imp(tests): Upstream Integration tests suite from sdk50 branch

- tests/solidity/suites/precompiles/package.json
- tests/solidity/yarn.lock
This PR updates Hardhat version to >=v2.20.0.
With previous version, we're getting an error when downloading the compiler:
```
Downloading compiler 0.8.18
Error HH502: Couldn't download compiler version list. Please check your internet connection and try again.
HardhatError: HH502: Couldn't download compiler version list. Please check your internet connection and try again.
...
Caused by: TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of ArrayBuffer
at writeFile (node:fs:2241:5)
```
Closes: #XXXX
---
I have...
Please add a note if the item is …
> chore(tests): update hardhat version

- precompiles/ics20/ICS20I.sol
- precompiles/staking/StakingI.sol
- precompiles/staking/testdata/StakingCaller.sol
- precompiles/vesting/testdata/VestingCaller.sol
- tests/solidity/suites/basic/contracts/Counter.sol
- tests/solidity/suites/basic/contracts/Storage.sol
- tests/solidity/suites/opcode/contracts/OpCodes.sol
This PR is fixing some annoying warning during solidity tests:
- add license to a test file.
- add pure to a function that is not interacting with the state.
Closes: #XXXX
---
I have...
I have...
> chore: fix solidity warnings

- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/types/access_list_tx.go
- x/evm/types/dynamic_fee_tx.go
- x/evm/types/legacy_tx.go
- x/evm/types/msg_test.go
Remove Chain ID constraint to 9000 / 9001
Closes: #XXXX
---
I have...
I have...
> imp(evm): Remove ChainID constraint

- Dockerfile
This PR fixes the building of the docker image by bumping the used version of `rclone`.
> fix(docker): Bump rclone version

- x/erc20/keeper/ibc_callbacks.go
Closes: #XXXX
---
I have...
I have...
> chore: remove repetitive words

- client/docs/swagger-ui/swagger-ui-bundle.js
- tests/nix_tests/utils.py
fix some typos
---
I have...
I have...
> chore: fix typos

- proto/ethermint/evm/v1/query.proto
- proto/ethermint/evm/v1/tx.proto
Closes: #XXXX
---
I have...
I have...
> chore: remove repetitive words in proto file

- LICENSE_FAQ.md
- README.md
This PR will change the legal email used in the repository.
Closes: #XXXX
---
I have...
I have...
> chore: update legal email

- Dockerfile
- mlc_config.json
This PR fixes docker image build.
It updates the corresponding dependencies to achieve this
Closes: #XXXX
---
I have...
I have...
> chore(docker): update docker deps

- .github/workflows/lint.yml
- Dockerfile
- app/app.go
- app/forks.go
- app/upgrades/v17/constants.go
- app/upgrades/v17/upgrades.go
- mlc_config.json
Update to latest version
Closes: #XXXX
---
I have...
I have...
> Update release branch with the latest version v16.0.4

- app/app.go
Register v17 upgrade logic
Closes: #XXXX
---
I have...
I have...
> Register v17 upgrade logic

- CHANGELOG.md
- SECURITY.md
This PR update the security policy of the Evmos chains codebase.
Closes: #XXXX
---
I have...
I have...
> chore: update security polity

- Dockerfile
Closes: #XXXX
---
I have...
I have...
> chore(deps): update docker dep

- CHANGELOG.md
- LICENSE_FAQ.md
This PR subsitutes references to Evmos SDK to evmOS.
Closes: #EVM-78
---
I have...
I have...
> change Evmos SDK into evmOS

- .github/workflows/ante-benchmark.yml
- .github/workflows/auto-format.yml
- .github/workflows/build.yml
- .github/workflows/dependencies.yml
- .github/workflows/e2e-test.yml
- .github/workflows/goreleaser.yml
- .github/workflows/lint.yml
- .github/workflows/solidity-test.yml
- .github/workflows/test.yml
- .golangci.yml
- CHANGELOG.md
- Makefile
- default.nix
- go.mod
- nix/default.nix
- tests/nix_tests/shell.nix
Closes: #XXXX
---
I have...
I have...
> chore(build): bump go to 1.22

- CHANGELOG.md
- client/config.go
Closes: #XXXX
---
I have...
I have...
> replace path.Join with filepath.Join

- app/app.go
- app/upgrades/v18/constants.go
- app/upgrades/v18/upgrades.go
Closes: #XXXX
---
I have...
I have...
> chore: add upgrade handler

- tests/e2e/Dockerfile.repo
Closes: #XXXX
---
I have...
I have...
> fix(e2e-test): update docker go version

- app/ante/cosmos/eip712.go
- app/app.go
- ibc/testing/endpoint.go
- rpc/types/block.go
- x/evm/keeper/state_transition_test.go
fix some typos in comments
Closes: #XXXX
---
I have...
I have...
> chore: fix some typos in comments

- x/erc20/keeper/evm_hooks.go
perform static checks first
Closes: #XXXX
---
I have...
I have...
> perf: Move the check moduleAddress before reading the db

- x/erc20/keeper/str_v2_test.go
Add some tests for strv2 bookkeeping
Closes: #XXXX
---
I have...
I have...
> chore(strv2): str bookkeping unit tests

- contracts/wevmos.go
- x/erc20/keeper/evm_hooks.go
- x/erc20/keeper/str_v2.go
- x/erc20/strv2/strv2_hooks_test.go
address the comments made on the original pr
Closes: #XXXX
---
I have...
I have...
> chore(strv2): address comments

- CHANGELOG.md
Add changelog
Closes: #XXXX
---
I have...
I have...
> chore(str): changelog

- CHANGELOG.md
fix changelog
Closes: #XXXX
---
I have...
I have...
>  chore(str): changelog 

- nix/default.nix
- nix/hermes.nix
Closes: #XXXX
---
I have...
I have...
> chore(nix-tests): update rust version

- x/staking/keeper/integration_test.go
- x/staking/keeper/msg_server_test.go
This PR makes the necessary changes to fix the tests in the `x/staking` module.
Other tests and linters may be failing. These will be addressed in other PRs
Closes: EVM-112
---
I have...
I have...
> chore(tests): migrate staking module wrapper tests

- Dockerfile
Closes: #XXXX
---
I have...
I have...
> chore(docker): update rclone dep

- CHANGELOG.md
- scripts/changelog_checker/config.py
Add a missing PR to the CHANGELOG. A fix to the changelog-checker is also introduced since broken after the removal of the outpost folder.
Closes: #XXXX
---
I have...
I have...
> fix(changelog): add missing PR to changelog

- CHANGELOG.md
- x/vesting/keeper/integration_test.go
- x/vesting/types/clawback_vesting_account.go
- x/vesting/types/clawback_vesting_account_test.go
Closes: #XXXX
---
I have...
I have...
> chore(vesting): add lockedUpVested delegations in LockedCoins calculation (#2507)

- CHANGELOG.md
- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/types/access_list_tx.go
- x/evm/types/dynamic_fee_tx.go
- x/evm/types/legacy_tx.go
- x/evm/types/msg_test.go
Closes: #XXXX
---
I have...
I have...
> imp(evm): Remove ChainID constraint (#2373)

- CHANGELOG.md
- precompiles/common/types.go
* fix(precompiles): update default precompiles bech32 addr
* add changelog entry
Closes: #XXXX
---
I have...
I have...
> fix(precompiles): update secp256r1 precompile bech32 addr (#2550)

- CHANGELOG.md
- x/evm/keeper/state_transition.go
* fix: duplicate event emitting
* CHANGELOG
* CHANGELOG
Closes: #XXXX
---
I have...
I have...
> fix(evm): duplicate event emitting (#2559)

- CHANGELOG.md
- x/evm/types/dynamic_fee_tx.go
Fix an error message returned in case of missing chainID for dynamic fee tx.
This PR should be backported in the V18.1.0 release too.
Closes: #XXXX
---
I have...
I have...
> chore: fix wrong error message

- .github/workflows/e2e-test.yml
- CHANGELOG.md
- precompiles/ics20/ics20.go
- precompiles/ics20/tx.go
- precompiles/ics20/types.go
- precompiles/ics20/utils_test.go
- tests/nix_tests/hardhat/contracts/ICS20FromContract.sol
- tests/nix_tests/test_ics20_precompile.py
- tests/nix_tests/test_precompiles.py
- tests/nix_tests/utils.py
- x/evm/keeper/precompiles.go
Closes: #XXXX
---
I have...
I have...
> chore(app): backport v18.1 changes to main

- app/post/setup_test.go
make function comments match function names
Closes: #XXXX
---
I have...
I have...
> chore: make function comments match function names

- precompiles/distribution/distribution_test.go
- precompiles/distribution/events_test.go
- precompiles/distribution/integration_test.go
- precompiles/distribution/tx_test.go
This PR only addresses the fixes for the unit and integration tests for the distribution precompile
```
go test ./precompiles/distribution/...                                                                                                      15s
ok      github.com/evmos/evmos/v18/precompiles/distribution     10.743s
```
Closes: #XXXX
---
I have...
I have...
> chore(distr-precompile): refactor new tests

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> chore: v19 changelog update

- .github/workflows/go-releaser-dry-run.yml
- Makefile
Closes: #XXXX
---
I have...
I have...
> fix: update goreleaser flags

- Dockerfile
Closes: #XXXX
---
I have...
I have...
> update docker dep

- .github/workflows/go-releaser.yml
Closes: #XXXX
---
I have...
I have...
> chore: add write permission to goreleaser

- app/ante/cosmos/authz.go
- app/tps_counter_test.go
- ibc/utils.go
- precompiles/authorization/types.go
- precompiles/common/precompile.go
- precompiles/erc20/tx.go
- precompiles/ics20/types.go
- precompiles/staking/tx.go
- precompiles/testutil/logs.go
- tests/e2e/upgrade/manager.go
- testutil/abci.go
The go linter version was bumped to v1.60.1 and we got some new linter errors.
This PR addresses those
Closes: #XXXX
---
I have...
I have...
> fix linter errors

- CHANGELOG.md
- x/evm/core/vm/interpreter.go
Closes: #XXXX
---
I have...
I have...
> fix: EIP for archive queries

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> chore: prepare changelog for v19.2.0

- app/app.go
- go.mod
- precompiles/staking/tx.go
- precompiles/staking/utils_test.go
- x/staking/keeper/msg_server.go
- x/staking/keeper/msg_server_test.go
- x/staking/module.go
Update wiring in staking module.
> fix!: update staking keeper wiring

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> prepare changelog for v20-rc1

- app/upgrades/v20/constants.go
Closes: #XXXX
---
I have...
I have...
> update upgrade constants for v20-rc1

- app/app.go
- app/upgrades/v20/constants.go
- app/upgrades/v20/upgrades.go
- app/upgrades/v20/upgrades_test.go
- tests/nix_tests/test_ics20_precompile.py
Closes: #XXXX
---
I have...
I have...
> add v20-rc2 upgrade to enable gov prec

- app/app.go
- app/upgrades/v20/upgrades.go
- app/upgrades/v20/upgrades_test.go
- testutil/integration/evmos/network/setup.go
Closes: #XXXX
---
I have...
I have...
> add expedited proposal params update to upgrade handler

- CHANGELOG.md
- app/app.go
- app/upgrades/v20/upgrades.go
- app/upgrades/v20/upgrades_test.go
Closes: #XXXX
---
I have...
I have...
> chore(upgrade): add fix denom meta logic

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> prepare changelog for v20-rc2

- CHANGELOG.md
- rpc/backend/call_tx.go
- testutil/integration/evmos/grpc/evm.go
Closes: #XXXX
---
I have...
I have...
> fix revert with error handling on test

- CHANGELOG.md
- app/app.go
- app/upgrades/v20/constants.go
- app/upgrades/v20/upgrades.go
- app/upgrades/v20/upgrades_test.go
Closes: #XXXX
---
I have...
I have...
> chore(upgrade): v20 upgrade logic

- CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
> prepare v20 chlog
