README.md

The dead link was removed until we have the webpage deployed to avoid confusion.

docs: dead link removed

---

docs/basics/gas.md

Two grammar fixes at lines 17 and 18.
Closes: #XXX
______
______
For admin use:

Update gas.md - grammar fixes

---

app/tps_counter_test.go
cmd/config/observability.go

Invoking `./init.sh` runs evmosd many times and unfortunately port
reuse on macOS and Linux takes a while hence most commands would fail.
This change temporarily disables it until it can be read from the
configuration file.
Fixes #84

cmd/config: disable observability until able to set it in config

---

CHANGELOG.md
x/intrarelayer/client/tx.go

Fix: Add missing convert-erc20 command [intrarelayer]

---

CHANGELOG.md
Dockerfile
Makefile
docs/quickstart/installation.md

Closes: #ENG-58
- Fixes `build-docker` command where the latest image created is `tharsis/evmos:COMMIT_SHA`
______
______
For admin use:

build: fix docker-build command

---

app/tps_counter.go

Reported offline by Fedekunze, the problem was that
we were unconditionally logging even in the case of
no blocks being processed.

app: only log TPS if value > 0

---

CHANGELOG.md
cmd/evmosd/root.go
go.mod
go.sum

Bumps Ethermint version to v0.9.0 and cleans up the CHANGELOG format.

build(deps): bump Ethermint version to v0.9.0

---

x/intrarelayer/types/msg.go
x/intrarelayer/types/msg_test.go
x/intrarelayer/types/proposal.go
x/intrarelayer/types/proposal_test.go

Closes: https://linear.app/tharsis/issue/ENG-315/intrarelayer-prefix-breaks-coin-conversion
With `RegisterERC20` the representative native Cosmos Coin has a `intrarelayer/ prefix` . This PR fixes the  validation during `ConvertCoin`.

Bug(Intrarelayer): Add validation of "intrarelayer/" prefix for Coin denominations in ConvertCoin

---

CHANGELOG.md
Makefile

Closes: #ENG-355
- fixes `version` command that picks the latest tag in the branch rather than all branches
______
______
For admin use:

Fix `evmosd version` 

---

app/tps_counter.go

Noticed while I was auditing through evmosd code that inside
the code that records TPS, that we have a typo in the calculation
of nFailed, that instead used latestNSuccessful, of which if enough
time is spent and the successful transactions have grown, while
the number of failed transactions stays still, this can cause
wrong TPS values to be reported.

app: fix typo in calculation of failed transactions in TPS value

---

go.mod
go.sum
x/inflation/keeper/epoch_mint_provisions_test.go
x/inflation/keeper/genesis_test.go
x/inflation/types/inflation_calculation.go
x/inflation/types/inflation_calculation_test.go

This PR adds a fix to mint the correct amount of inflation. With this fix the `epochMintProvision` is multiplied by the power reduction (10^18) as the calculation is based on `evmos` and the issued tokens need to be given in `aevmos`.

bug(inflation): multiply daily epoch mint provision calculation by Power reduction

---

x/claims/spec/README.md
x/erc20/spec/README.md
x/incentives/spec/README.md
x/inflation/spec/README.md

This PR fixes links in the [specs](https://evmos.dev/).
Closes https://linear.app/tharsis/issue/ENG-526/link-to-parameters-broken-in-inflation-spec-content-overview

spec(bug): fix module table of content links (ENG-526)

---

docs/mainnet/join.md

Githubs LFS (large file storage) only pulls large files explicitly.

docs(genesis): updated genesis.json instructions

---

CHANGELOG.md
x/erc20/keeper/evm_hooks.go

```
11:06AM ERR tx post processing failed error="EVM hook keeper.Hooks failed: EVM Hook is currently disabled: internal ethereum token mapping error" module=evm
```

fix: return nil on erc20 evm hook

---

CHANGELOG.md
cmd/evmosd/cmd_test.go
cmd/evmosd/root.go

Throw and error when `--ledger` flag is passed in cli. This is temporary while we have support for the ledger in an immediate future.
Closes: #XXX
______
I have...
I have...
______
I have...

bug: throw an error when ledger flag is passed

---

docs/guides/upgrades/upgrade_node.md

______
I have...
I have...
______
I have...

docs: add `v1.0.0` to cosmovisor install

---

CHANGELOG.md
app/app.go
app/forks.go
app/upgrades/v2/constants.go
go.mod
go.sum
x/claims/keeper/migrations.go
x/claims/migrations/v2/migration.go
x/claims/module.go
x/erc20/keeper/evm_hooks.go
x/erc20/keeper/migrations.go
x/erc20/migrations/v2/migration.go
x/erc20/module.go

______
I have...
I have...
______
I have...

app: upgrade v1.1.2 to v2

---

x/claims/migrations/v2/migration.go

Closes: #XXX
______
I have...
I have...
______
I have...

Don't use GetParams

---

CHANGELOG.md
x/claims/migrations/v2/migration.go

- release: bump Evmos version to v2 (#351)
- app: upgrade handler for v2 (#352)
- Merge pull request from GHSA-5jgq-x857-p8xw
- fix: don't use GetParams (#363)

release: v2.0.1 changelog

---

CHANGELOG.md
x/claims/genesis.go
x/claims/genesis_test.go

While attempting to export the state to genesis and create a testnet, it was discovered that the InitGenesis.go hadn't considered and export after claims were completed.
Closes: #XXX
______
I have...
I have...
______
I have...

Fixing subtle bug in genesis verification post-export

---

.github/workflows/lint.yml

Use golangci-lint for [1.44]( https://github.com/golangci/golangci-lint/releases/tag/v1.44.2)
We get an [error](https://github.com/tharsis/evmos/actions/runs/1956985889) in 1.42, but not in 1.44 
______
I have...
I have...
______
I have...

Use golangci for 1.44

---

x/claims/keeper/ibc_callbacks.go
x/claims/keeper/ibc_callbacks_test.go

If sender == recipient, ibc claims callback returns error. Which doesnt allow the recovery code to execute.
If we execute the recovery code first, and then it fails on claim. The recovery will execute, but the ibc will revert the tx
Closes: #XXX
______
I have...
I have...
______
I have...

[ENG-99] allow recovery if failed claim

---

CHANGELOG.md
init.sh
x/claims/keeper/claim.go
x/claims/keeper/claim_test.go
x/claims/keeper/ibc_callbacks_test.go

This PR simplifies the merge/migrate logic for claiming records with the  IBC `OnRecvCallback`.
Note: Please confirm that it should not be possible for non-evmos claims records to exist, which have actions claimed. The rationale behind this is that non-evmos addresses with claims records
- cannot claim VOTE, DELEGATE or EVM_ACTIONS
- always have their claims record merged/migrated on the first attempt of performing the IBC callback

ENG-109 - impr(claims): remove claims merge/migrate cases where sender already completed an action as they are never reached

---

CHANGELOG.md
x/vesting/keeper/msg_server.go
x/vesting/keeper/msg_server_test.go
x/vesting/types/clawback_vesting_account.go
x/vesting/types/clawback_vesting_account_test.go

Closes: #XXX
______
I have...
I have...
______
I have...

fix: clawback before vesting start time

---

CHANGELOG.md
x/vesting/keeper/msg_server.go

Closes: #XXX
______
I have...
I have...
______
I have...

fix: remove `SpendableCoins` from vesting

---

CHANGELOG.md
x/claims/keeper/claim.go
x/claims/keeper/claim_test.go
x/claims/keeper/ibc_callbacks_test.go
x/claims/spec/04_hooks.md
x/claims/types/params.go

This PR adds functionality to retain claims records instead of deleting them once the last action is claimed. I also added the `DefaultEVMChannels` to the `DefaultAuthorizedChannels` as I understand that the requirement for an EVM chain to claim records is that it also has to be an authorized chain.

impr(claims): Retain claims records when all actions have been completed

---

CHANGELOG.md
app/app.go

Closes: #XXX
______
I have...
I have...
______
I have...

fix: upgrade client router key

---

x/erc20/keeper/evm.go
x/erc20/keeper/evm_hooks.go
x/erc20/keeper/mint.go
x/erc20/keeper/msg_server.go
x/erc20/keeper/proposals.go
x/erc20/spec/03_state_transitions.md
x/erc20/spec/05_hooks.md

This PR adds minor improvements from performing a state machine audit on the x/erc20 module:
- improved comments
- moved evm relevant helper methods to `evm.go`
- updated specs
- are the migrations necessary?
- Toggle token pair: Should we revert the token transfer through the hook if a token pair is disabled?
-  Add tests make sure that if ConvertERC20 is called, that the Hook doesn't trigger

audit(erc20): state machine audit

---

x/erc20/client/cli/tx.go
x/erc20/keeper/mint.go
x/erc20/types/errors.go

I noticed that the template for registering a coin is not accurate and doesn't pass stateless validations.

impr(erc20): fix cli register ibc coin template

---

x/fees/types/msg.go
x/fees/types/msg_test.go

We already charge gas for address derivation. But I am also adding the second limitation suggested here https://github.com/tharsis/evmos/pull/436#pullrequestreview-937344416
> we should limit the number of elements in the nonces field (say to 20 elements max)
Closes: #XXX
______
I have...
I have...
______
I have...

fees: limit address derivation to 20 iterations at registration

---

CHANGELOG.md
x/claims/client/cli/query.go
x/claims/keeper/ibc_callbacks.go
x/claims/keeper/ibc_callbacks_test.go
x/claims/spec/06_parameters.md
x/claims/spec/07_clients.md

Closes: #XXX
______
I have...
I have...
______
I have...

fix: remove dup set claims record + CLI update

---

x/claims/spec/07_clients.md

The x/claims REST endpoint shows /evmos/claims/v1/claims_record/{address}, but it should be claims_records as written in https://github.com/tharsis/evmos/blob/main/proto/evmos/claims/v1/query.proto#L29
Closes: #621 
______
I have...
I have...
______
I have...

fix: typo in x/claims REST endpoint docs

---

CHANGELOG.md
x/erc20/client/cli/tx.go
x/erc20/types/proposal.go
x/erc20/types/proposal_test.go

This PR removes the `Name` and `Symbol` checks so that devs can specify 
* a `Symbol` like `OSMO` instead of `ibcOSMO-0` and
* a `Name` like `Osmo` instead of `Osmo channel-0`

impr(erc20): remove enforcing ibc and channel names during `RegisterCoin`

---

CHANGELOG.md
x/vesting/client/cli/tx.go

`create-vesting-account` cli cmd was incorrectly linked. 
Closes: #XXX
______
I have...
I have...
______
I have...

[ENG-404] Remove incorrect vesting command

---

app/upgrades/v5/upgrades.go

We should aim to divert testnet and mainnet versions as little as possible, so that our testnet environment reflects changes on mainnet better. Therefore this PR applies mainnet migrations also to testnet. 
Part of [ENG-398](https://linear.app/evmos/issue/ENG-398/create-upgrade-handler-for-v5-release)

upgrade(app): remove mainnet condition for migrations that should also apply to testnet

---

Makefile

This PR adds the missing the `protoc-gen-go-grpc` plugin in `make tools`

impr(makefile): update protoc-gen installation

---

app/upgrades/v5/constants.go

This PR sets the blockheight for mainnet to [837,500](https://www.mintscan.io/evmos/blocks/837500) (3pm UTC next monday) and testnet to [1,762,500](https://testnet.mintscan.io/evmos-testnet/blocks/1762500) (3pm UTC this Thusday)

upgrade(v5): add upgrade heights

---

x/README.md
x/feesplit/client/cli/tx.go
x/feesplit/genesis_test.go
x/feesplit/spec/01_concepts.md

This PR adds missing genesis import export tests and a notes for projects to deploy their contracts from a project owned account, rather than from the account of an individual contributor. 
Closes: ENG-453 https://linear.app/evmos/issue/ENG-453/completeness-audit  and ENG-522 https://linear.app/evmos/issue/ENG-522/fee-deployer-could-be-malicious

audit(feesplit): completeness audit

---

app/app.go
app/upgrades/v6/upgrades.go
app/upgrades/v7/constants.go
app/upgrades/v7/upgrades.go
app/upgrades/v7/upgrades_test.go
go.mod
go.sum

This PR migrates the testnet faucet balance.
Closes ENG-151: https://linear.app/evmos/issue/ENG-151/migrate-inaccessible-balance-of-secp-faucet-account-to-new-address

migration(testnet): add v7 migration for moving inacessible faucet address

---

CHANGELOG.md
go.mod
go.sum

This PR bumps the Ethermint version that includes a backport patch for the `eth_getBalance` JSON-RPC endpoint in order to query historical archive nodes:
[- fix(rpc): optimize `eth_getBalance` endpoint (#1169)
](https://github.com/evmos/ethermint/pull/1169/files)
Related issue: https://linear.app/evmos/issue/ENG-577/release-ethermint-and-evmos-patches-for-historical-archive-nodes

release: v2.0.2 changelog

---

CHANGELOG.md
go.mod
go.sum

This PR bumps the Ethermint version that includes a backport patch for the `eth_getBalance` JSON-RPC endpoint in order to query historical archive nodes:
[- fix(rpc): optimize `eth_getBalance` endpoint (#1169)
](https://github.com/evmos/ethermint/pull/1169/files)
Related issue: https://linear.app/evmos/issue/ENG-577/release-ethermint-and-evmos-patches-for-historical-archive-nodes

release: v4.0.2 changelog and bump ethermint version

---

CHANGELOG.md
app/app.go
cmd/evmosd/genaccounts.go
go.mod
go.sum
x/erc20/keeper/evm_hooks.go

This PR bumps the Ethermint version that includes a backport patch for the `eth_getBalance` JSON-RPC endpoint in order to query historical archive nodes:
[- fix(rpc): optimize `eth_getBalance` endpoint (#1169)
](https://github.com/evmos/ethermint/pull/1169/files)
Related issue: https://linear.app/evmos/issue/ENG-577/release-ethermint-and-evmos-patches-for-historical-archive-nodes

release: v1.1.3 changelog

---

.github/workflows/goreleaser.yml
Makefile

This PR changes the release github action to use the original make script that was replaced [here](https://github.com/evmos/evmos/commit/bd2a9a569dd4a385676029d2d6aae307db54eaa2) using, but now using go v.18

ci(goreleaser): revert to make command

---

docs/validators/upgrades/upgrades.md
x/feesplit/spec/README.md

This PR adds the `v6.0.2` upgrade to the docs and corrects the feesplit name in the navigation
Closes [ENG-605](https://linear.app/evmos/issue/ENG-605/update-docs-with-v6-upgrade-height)

docs(upgtade): add manual patch release upgrade v6.0.2

---

Makefile

This PR fixes the makefile so that go1.18 can work. 
______
I have...
I have...
______
I have...

bug: Makefile doesn't work with go 1.18

---

CHANGELOG.md
x/feesplit/module.go
x/feesplit/types/codec.go
x/feesplit/types/msg.go

Without the amino codec registered we can not send EIP712 transactions, error on submit:
```{
tx_response: {
height: '0',
txhash: '2D17346A4DEEBE9ADA74A06F328DA69BBCC8907623FC910C9D8E9C00AC1FC34D',
codespace: 'sdk',
code: 4,
data: '',
raw_log: 'signature verification failed; please verify account number (11) and chain-id (evmos_9000-1): failed to pack and hash typedData primary type: there is extra data provided in the message (2 < 4) [evmos/ethermint@v0.19.0/ethereum/eip712/eip712.go:34]: unauthorized',
logs: [],
info: '',
gas_wanted: '3000000',
gas_used: '84492',
tx: null,
timestamp: '',
events: []
}
}
```
Closes: #XXX
______
PR review …

feat: add amino codec to feeSplit

---

CHANGELOG.md
cmd/evmosd/root.go

Add new `prune` command to cli
______
I have...
I have...
______
I have...

imp(cmd): Add prune command

---

CHANGELOG.md
cmd/evmosd/root.go

the configuration can be changed in app.toml
```
iavl-cache-size = 781250
iavl-disable-fastnode = true
```
PR done initially by @giansalex but opening because of time constraints 🙏 
Closes: #XXX
______
I have...
I have...
______
I have...

Set IAVL config

---

app/app.go

Removing duplication from `main`. This doesn't occur on the release branch.

fix: remove duplicated upgrade handler

---

docs/validators/upgrades/upgrades.md

This PR adds missing upgrades to docs. This task should be performed after every release, as described in the post-release items in the release guide. 
Closes: https://linear.app/evmos/issue/ENG-958/add-missing-upgrades-to-docs

docs(upgrades): add missing mainnet and testnet upgrades to list of upgrades

---

.github/workflows/build.yml
.github/workflows/goreleaser.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.golangci.yml
CHANGELOG.md
Makefile
README.md
docs/validators/quickstart/installation.md
docs/validators/upgrades/manual.md
go.mod
networks/local/evmos/Dockerfile

Bumping to gov1.19 to gain parity with ethermint and support comment by @faddat (https://github.com/evmos/evmos/pull/1023)
Part of https://linear.app/evmos/issue/ENG-953/create-release-candidate-v10-rc1-on-evmos

deps(go): Bump to go 1.19

---

CHANGELOG.md
go.mod
go.sum

Partially closes https://linear.app/evmos/issue/ENG-953/create-release-candidate-v10-rc1-on-evmos
Backports ics23 dragonberry replace in go.mod to `main` as mentioned in the [Cosmos SDK release](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.4). 
Included in the recent releases https://github.com/evmos/evmos/pull/965 and https://github.com/evmos/evmos/pull/976
Thank you @faddat for initiating this in https://github.com/evmos/evmos/pull/1021

deps: backport  ics23 dragonberry fix to main

---

docs/validators/upgrades/automated.md

Updates the cosmovisor command as described [here](https://docs.cosmos.network/main/tooling/cosmovisor):
> `run` - Run the configured binary using the rest of the provided arguments.
Closes: https://linear.app/evmos/issue/ENG-955/test-upgrading-to-release-candidates-rc-with-cosmovisor

docs(upgrades): update cosmovisor command

---

CHANGELOG.md
ibc/testing/app.go
ibc/testing/chain.go
ibc/utils.go
ibc/utils_test.go
types/errors.go
types/utils.go
types/utils_test.go

Utils and tests required for erc20 ibc middleware
Closes: #XXX
______
I have...
I have...
______
I have...

feat(ibc): utils for erc20 middleware

---

CHANGELOG.md
app/app.go
x/ibc/transfer/ibc_module.go
x/ibc/transfer/keeper/keeper.go
x/ibc/transfer/keeper/keeper_test.go
x/ibc/transfer/keeper/msg_server.go
x/ibc/transfer/keeper/msg_server_test.go
x/ibc/transfer/module.go
x/ibc/transfer/types/interfaces.go

Wrapper for `x/ibc/transfer` module that allow us to convert outgoing ibc transfer from erc20 tokens to their cosmos denomination (trough `erc20` module)
Closes: #XXX
______
I have...
I have...
______
I have...

feat (ibc): erc20 conversion trough  `transfer` module 

---

CHANGELOG.md
docs/protocol/telemetry.md
x/erc20/keeper/msg_server.go
x/incentives/keeper/distribution.go
x/recovery/keeper/ibc_callbacks.go
x/revenue/keeper/evm_hooks.go

This PR removes the labels that result in unbound cardinality as it will keep creating new metrics with different labels with each call.
Closes: #1050 
______
I have...
I have...
______
I have...

Fix unbound metrics and remove labels that keep increasing

---

CHANGELOG.md
Makefile
cmd/evmosd/root.go

The `evmosd version` currently always shows the latest tag. This fix changes the behaviour to show the version of the currently installed binary

bug(MAKEFILE): fix `evmosd version` cmd to show either tag or last commit

---

local_node.sh

This PR adds a check if the `~/.tmp-evmosd` folder exists already when executing `local_node.sh`.
The user can choose if the existing blockchain from that directory should be used or if it shall be overwritten.
This is an improvement because it enables two use-cases for the local node script (create new or continue) as well as make sure that any user is fully aware that this script will completely remove the previous configuration upon selection.
----
Closes #1113 and ENG-1091

imp: add option to overwrite in local node script

---

local_node.sh

removed `create_empty_blocks` and `create_empty_blocks_interval` config in `./local_node.sh` script because those options does not works in cosmos-sdk
Source: [cosmos/cosmos-sdk#746](https://github.com/cosmos/cosmos-sdk/issues/746)
> Currently the appHash changes every block, since the CommitMultiStore encodes the version and that version changes on every block. Due to that --consensus.create_empty_blocks = false does not work, with the current sdk. Tendermint expects that the appHash doesn't change and only then stops producing blocks.
@#jaekwon @#ebuchman What was the outcome of your discussion around the constantly changing appHash with the MultiStore? Also, do we want the functionality of no_empty_blocks? I think it would be nice to have the ability to only produce blocks every minute …

imp: remove create_empty_blocks and create_empty_blocks_interval

---

Makefile
app/app.go

This PR mirrors evmos/ethermint#1507 on the Evmos repository.

chore: remove simulations

---

docs/validators/setup/mempool.md

This PR will add a hint for developers to the mempool docs, that it is necessary to restart a running node after changing the `config.toml` file.

imp (docs): add remark about restarting a node after changes to mempool config

---

CHANGELOG.md
go.mod
go.sum

This PR bumps Ethermint to version [v0.20.0-rc5](https://github.com/evmos/ethermint/releases/tag/v0.20.0-rc5).

build (deps): bump Ethermint version to v0.20.0-rc5

---

app/upgrades/v10/constants.go

This PR updates the version used in constants.go to v10.0.0-rc3

chore: update version to v10.0.0-rc3 in upgrade name and links

---

CHANGELOG.md
app/upgrades/v10/constants.go
cmd/evmosd/root.go
go.mod
go.sum

This PR does the following:
- revert default mempool configuration back to `v0` (FIFO mempool) as we have seen this being detrimental to node performance
- update our fork of the Cosmos SDK to v0.46.7
- prepare `v10/constants.go` for the release of v10.0.0-rc4
- add some missing changelog entries, that were only on the release branch as of yet
----
Closes ENG-1255

chore (app, deps): address open points for rc4 release

---

CHANGELOG.md
app/upgrades/v11/constants.go
app/upgrades/v11/upgrades.go
app/upgrades/v11/upgrades_test.go
docs/protocol/moduleaccounts.md

Add account number and sequence to migrated IBC escrow accounts.
During testing the new changes on the last testnet upgrade, it was observed that the migrated accounts had an `account_number == 0`
```shell
'@type': /cosmos.auth.v1beta1.ModuleAccount
base_account:
account_number: "0"
address: evmos1a53udazy8ayufvy0s434pfwjcedzqv345dnt3x
pub_key: null
sequence: "0"
name: "ics20-1\0transfer/channel-0"
permissions: []
```
This PR includes the changes to fix this by using the `account_number` that belongs to the existing account
----
Closes ENG-1344

fix(upgrade): add account number and sequence to migrated IBC escrow accounts

---

CHANGELOG.md
docs/users/basics/gas.md
x/inflation/client/cli/query.go
x/inflation/keeper/grpc_query.go
x/inflation/keeper/hooks.go
x/inflation/keeper/inflation.go
x/inflation/keeper/inflation_test.go
x/inflation/migrations/v3/migrate_test.go

Minor improvements to the inflation module from debugging

imp(inflation): remove dup store calls and improve perf

---

testutil/network/network.go

Fixes a previously closed issue: https://github.com/evmos/evmos/issues/378
The solution mentioned in the issue of running v=1 validators does not address the problem.
Currently the `evmosd testnet start` cmd fails with the default option of 4 validators. This is because it tries to bind multiple times to the JSON RPC 8545 port. Defaulting the `JSONRPC.Enable` flag to `false` solves the problem, leaving just 1 node  exposing the endpoint.

fix: testnet start cmd for multiple validators

---

CHANGELOG.md
app/ante/cosmos/authz.go
app/ante/cosmos/authz_test.go

----
Closes https://linear.app/evmos/issue/ENG-1512/run-authz-limiter-decorator-on-delivertx

chore(ante) refactor to run authz anteHander in deliverTx mode

---

CHANGELOG.md
app/ante/cosmos/authz_test.go
app/ante/cosmos/setup_test.go
app/ante/cosmos/utils_test.go
app/ante/evm/ante_test.go
app/ante/evm/fee_market_test.go
app/ante/evm/utils_test.go
testutil/abci.go
testutil/tx/cosmos.go
testutil/tx/eip712.go

chore(tests) add EIP712 tx util funcs

---

CHANGELOG.md
app/ante/evm/fee_checker.go
app/ante/evm/fee_checker_test.go
x/evm/types/utils.go

- add check on dynamic fee
- update check
----
Closes #XXX

fix(ante): add additional check to FeeChecker

---

CHANGELOG.md
app/ante/evm/fee_market.go
app/ante/evm/fee_market_test.go

----
Closes https://linear.app/evmos/issue/ENG-1563/tx-timeout-error

fix(ante) add block gas limit check for cosmos txs

---

CHANGELOG.md
app/ante/handler_options.go
app/ante/handler_options_test.go

----
Add TxFeeChecker check on handler options
Closes #XXX

Add TxFeeChecker requirement

---

.goreleaser.yml
CHANGELOG.md

Fix go-releaser naming to be consistent with previous version binaries
----
Closes #XXX

imp(ci) fix go-releaser naming

---

app/app.go
x/revenue/v1/keeper/evm_hooks.go
x/revenue/v1/keeper/integration_test.go
x/revenue/v1/keeper/keeper.go
x/revenue/v1/keeper/utils_test.go
x/revenue/v1/types/interfaces.go

This PR adds automatic routing of gas fees registered through the `revenue` module targeted at precompiled contracts directly into the community pool.
----
Closes ENG-1861

feat(revenue): route gas fees paid from calling precompiles to community pool

---

CHANGELOG.md
x/evm/keeper/grpc_query.go

Cherry-pick bug fixed in ethermint but missing on evmos https://github.com/evmos/ethermint/pull/1591
Look [here in evmos](https://github.com/evmos/evmos/blob/9c7def2f2468294d8defe7ed218215f77448509d/x/evm/keeper/grpc_query.go#L394) and [here in ethermint](https://github.com/evmos/ethermint/blob/07cf2bd2b1ce9bdb2e44ec42a39e7239292a14af/x/evm/keeper/grpc_query.go#L406), both referenced from their `main` branch
> > block height already minus by one in rpc
> >
> > https://github.com/evmos/ethermint/blob/57ed355c985d9f3116aba6aabfa2ee0f3f38e966/rpc/backend/tracing.go#L110-L114
> > 
> > Oh no, so currently it keep minus by one in grpc so actually minus by 2? If calling via API debug_traceTransaction?
> Fixing BlockNumber from [request](https://github.com/evmos/ethermint/blob/57ed355c985d9f3116ab …

fix(rpc): wrong block number in debug trace related api (cherry-pick)

---

CHANGELOG.md
app/app.go

Changes introduced on cosmos-sdk v0.47 make some txs fail when submitting a governance proposal due to the length of the text in the summary.
Previously, this was not checked, and this was not an issue ([see here](https://github.com/evmos/cosmos-sdk/blob/e925a63f7961edda08f12efdfeb0a0bba49783f7/x/gov/keeper/proposal.go#L15-L18)). But on v0.47 of the SDK, the `MaxMetadataLen` is used to check for `title` and `summary` fields of the proposal ([source code](https://github.com/evmos/cosmos-sdk/blob/201256f9d1944e590f06d3804cbea095d8a2c5dd/x/gov/keeper/proposal.go#L21-L31))
Solution: Increase the `MaxMetadataLen` configuration in the gov keeper
----
Closes #XXX

chore: update gov config

---

local_node.sh

This PR adds the following improvements to the `local_node.sh` script:
- reuse same seed phrases as in E2E test script, so that the testing addresses are not overwritten everytime (helps with reproducibility of testing flows)
- add flag parsing
- `-y`: overwrite existing chain data and reset everything
- `-n`: do _not_ overwrite existing chain data, continue from last block
- `--no-install`: skip installation of the binary (useful if correct version is already installed)
----
Closes ENG-2034

imp(tests): improvements to local node script

---

CHANGELOG.md
precompiles/authorization/IICS20Authorization.sol
precompiles/common/Types.sol
precompiles/common/types.go
precompiles/ics20/ICS20I.sol
precompiles/ics20/abi.json
precompiles/ics20/approve.go
precompiles/ics20/approve_test.go
precompiles/ics20/events.go
precompiles/ics20/events_test.go
precompiles/ics20/integration_test.go
precompiles/ics20/query.go
precompiles/ics20/query_test.go
precompiles/ics20/types.go
precompiles/ics20/utils_test.go
precompiles/testutil/contracts/InterchainSender.sol

This PR is the first of a series aiming to refactor the ICS20 Extension Approvals to be more aligned with IERC20 Approvals. 
- Removed `Revoke` specific Event, now it will just emit `Approve` with 0 `Allocation`
- Move `Allocation` to common package
----
Closes #XXX

fix(ics20): Refactor ICS20Authorization to use Allocations

---

CHANGELOG.md
Makefile
client/testnet.go
cmd/evmosd/testnet.go

I noticed that you have removed the `Crisis` module in the `NewEvmos` function in https://github.com/evmos/evmos/pull/1847, but you forgot to remove the corresponding logic in the `initGenFiles` function, which caused a panic error when using the command `evmosd testnet init-files --v 2 --output-dir ./nodes --chain-id evmos_9000-1 --keyring-backend test`. I have made a simple fix for this.
----
Closes #XXX

fix(testnet): remove the crisis module causing an error when using the `evmosd testnet init-files` command

---

CHANGELOG.md
app/app.go
app/upgrades/v14_2/setup_test.go
app/upgrades/v14_2/upgrades.go
app/upgrades/v14_2/upgrades_test.go
app/upgrades/v14_2/utils_test.go
x/evm/migrations/v5/migrate_test.go
x/evm/types/params.go
x/evm/types/params_test.go

This PR adds the necessary logic to enable [EIP 3855](https://eips.ethereum.org/EIPS/eip-3855) during the v14.2.0 upgrade.
More context can be found in [this Medium article](https://medium.com/coinmonks/push0-opcode-a-significant-update-in-the-latest-solidity-version-0-8-20-ea028668028a).
----
Closes ENG-2149

imp(evm): enable EIP 3855 during upgrade

---

CHANGELOG.md
rpc/backend/backend.go
rpc/backend/blocks.go
rpc/backend/call_tx.go
rpc/backend/chain_info.go
rpc/backend/utils.go
rpc/namespaces/ethereum/eth/api.go
tests/nix_tests/configs/discard-abci-resp.jsonnet
tests/nix_tests/test_no_abci_resp.py

When setting the configuration parameter `discard_abci_responses = true`, all JSON-RPC methods that rely on `TendermintBlockResult` (e.g.: `eth_gasPrice`, `eth_getBlockByNumber`, `eth_getBlockByHash`,  `eth_getTransactionByHash`,  `eth_getTransactionReceipt`, `eth_getTransactionLogs`, `eth_feeHistory`) will not return the expected result (usually `null`) and in some cases cause a panic.
For example, in  `eth_gasPrice` the error logs are:
```
4:48PM INF Served eth_gasPrice conn=10.100.1.9:40160 duration=594.644458 err="method handler crashed" module=geth reqid=2231
4:48PM ERR RPC method eth_gasPrice crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 109462359 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1() …
```

fix(rpc): handle case when node is not persisting abci responses

---

CHANGELOG.md
precompiles/outposts/stride/setup_test.go
precompiles/outposts/stride/utils_test.go

This PR adds the basic unit testing setup which utilizes functionality from the ibc-go repository to mock 2 chains and establish channels between them. A follow up PR will refactor this to use our new integration test setup.
----
Closes #XXX

chore(stride): Add stride outpost unit testing setup

---

CHANGELOG.md
precompiles/outposts/osmosis/osmosis.go
precompiles/outposts/osmosis/types.go
precompiles/outposts/osmosis/types_test.go

This PRs aims to add additional types + associated tests for the osmosis outpost

imp(osmosis): Outpost missing types

---

CHANGELOG.md
precompiles/common/abi.go
precompiles/outposts/osmosis/osmosis.go
precompiles/outposts/stride/stride.go

This PR aim to remove the ABI logic from inside the outpost implementations to use the specific function inside precompiles common package.
----
Closes #XXX

imp(outposts): common function to read ABI

---

precompiles/erc20/erc20.go
precompiles/erc20/query.go
precompiles/erc20/tx.go

feat(erc20): precompile setup

---

CHANGELOG.md
precompiles/common/abi.go
precompiles/erc20/erc20.go
precompiles/erc20/events.go
precompiles/erc20/events_test.go
precompiles/erc20/setup_test.go
precompiles/erc20/types.go
precompiles/outposts/osmosis/events_test.go

This PR adds tests to the ERC20 precompile event emitting.
----
Closes ENG-2282

imp(erc20,tests): add tests for ERC20 precompile events

---

CHANGELOG.md
precompiles/authorization/types.go

I noticed we had an unused and outdated util function laying around to check distribution approval arguments. This PR removes that function.

chore(precompiles): remove outdated distribution authorization checks

---

CHANGELOG.md
app/ante/cosmos/min_price_test.go

I saw some tests in it, deliverTx can pass, but deliverTxSimulate cannot. This is obviously wrong. Because the former has stricter inspections than the latter

fix(test): fix the problem about deliverTxSimulate in test app/ante/cosmos/min_price_test.go

---

CHANGELOG.md
precompiles/erc20/tx.go

feat(erc20): ERC-20 transactions

---

CHANGELOG.md
precompiles/erc20/approve.go
precompiles/erc20/query.go

feat(erc20): ERC-20 approval

---

CHANGELOG.md
precompiles/erc20/erc20.go
precompiles/erc20/erc20_test.go

This PR adds unit tests for the `IsTransaction` and `RequiredGas` functions. It also extracts the gas values to constants so it's possible to also reference those in the integration tests.
----
Closes ENG-2316

tests(erc20): add IsTransactions and RequiredGas tests

---

CHANGELOG.md
precompiles/bank/IBank.sol
precompiles/bank/abi.json
precompiles/bank/bank.go
precompiles/bank/query.go
precompiles/bank/types.go

----
This PR adds the `supplyOf` query to the bank extension. Tests will follow in a separate PR.
Closes #XXX

imp(bank): Add supplyOf query

---

CHANGELOG.md
precompiles/erc20/approve.go
precompiles/erc20/approve_test.go
precompiles/erc20/errors.go
precompiles/erc20/errors_test.go
precompiles/erc20/query.go
precompiles/erc20/query_test.go
precompiles/erc20/tx.go
precompiles/erc20/tx_test.go

This PR takes some of the findings from #2044 and aligns our ERC20 EVM extension with the way things are handled on the actual Solidity contracts.

imp(erc20): minor alignments between ERC20 extension and contracts

---

CHANGELOG.md
precompiles/bank/setup_test.go
precompiles/outposts/stride/events_test.go
precompiles/outposts/stride/setup_test.go
precompiles/outposts/stride/tx_test.go
precompiles/outposts/stride/utils_test.go
precompiles/werc20/integration_test.go
testutil/integration/evmos/network/network.go
testutil/integration/evmos/utils/unit.go

----
This PR adds the Evmos metadata to the integration testing setup to avoid having register it in each separate testing scenario. Additionally thanks to @0xstepit and @facs95 adding the IBC coordinator to the setup we can significantly trim down the Stride testing setup
Closes #XXX

fix(tests): Add Evmos metadata to integration network and refactor Stride and Osmosis Outpost tests

---

CHANGELOG.md
app/db.go
precompiles/distribution/distribution.go
precompiles/erc20/erc20.go
precompiles/werc20/werc20.go

The `versiondb` directory was created with permission `os.ModePerm` (777) which is insecure so I changed it to generic permission 750.
In additional, I rename some wrong variable name which pointed out in #2058

fix(db): change versiondb directory permission from 777 (insecure) to 750 (general)

---

CHANGELOG.md
precompiles/erc20/errors.go
precompiles/erc20/query.go
precompiles/erc20/query_test.go

…ies implemented
This PR aligns the response from failing metadata queries with the ERC20 contracts which don't expose their metadata. These return the general "execution reverted" error with no further info, which is what we've implemented here.

imp(erc20): align metadata query errors with ERC20 contracts

---

CHANGELOG.md
precompiles/erc20/approve.go
precompiles/erc20/approve_test.go
precompiles/erc20/errors.go
precompiles/erc20/query.go
precompiles/erc20/tx.go

This PR is the final PR to adjust differences in error handling between the ERC20 smart contracts and our EVM extension, which have been identified on #2044.
It adjusts the surfaced errors for the Increase and Decrease allowance methods.

imp(erc20): align allowance adjustment errors with erc20 contracts

---

CHANGELOG.md
app/app.go
go.mod
go.sum
precompiles/outposts/osmosis/osmosis.go
x/evm/keeper/precompiles.go
x/ibc/transfer/types/channels.go

This PR:
- Change the Cosmosd SDK fork to the one with getter of ChainID
- Add a channel selector depending on the ChainID
- Add transfer ibc app channels for outpost in separate file.

Add channel selector from chainID

---

CHANGELOG.md
Makefile
client/docs/swagger-ui/swagger.json

Problem: `Makefile` currently pull `main`/`master` branches of multiple repositories for swagger gen.
This would cause wrong docs generated, eg: your chain using ibc v7 but latest ibc is v8 thus generated swagger is wrong
___
I'm on metered connection so inconvenient to test, feel free to correct, update or even rework in another PR as you wish.

fix(swagger): use correct version of proto dependencies to generate swagger

---

CHANGELOG.md
testutil/integration/evmos/utils/bank.go
testutil/integration/evmos/utils/bank_test.go

This PR adds a helper function to more easily check expected balances during tests.

imp(tests): add utility to check balances in tests

---

x/evm/types/params.go

This PR extends the `HasCustomPrecompiles` method for the EVM params to also check for active dynamic precompiles. This is important, because when executing an EVM transaction, the EVM only is populated with Evmos' precompiles if this check returns true.
Closes: XAP-143

imp(evm): Check for dynamic extensions during EVM initialization

---

precompiles/distribution/integration_test.go
precompiles/distribution/setup_test.go
precompiles/vesting/events.go
precompiles/vesting/integration_test.go
precompiles/vesting/query_test.go
precompiles/vesting/setup_test.go
precompiles/vesting/tx_test.go
precompiles/vesting/utils_test.go
testutil/integration/evmos/factory/factory.go
testutil/integration/evmos/factory/vesting.go
testutil/integration/evmos/network/abci.go
testutil/integration/evmos/network/network.go
testutil/integration/evmos/network/setup.go
x/epochs/keeper/abci_test.go
x/epochs/keeper/grpc_query_test.go
x/evm/keeper/benchmark_test.go
x/evm/keeper/keeper_test.go
x/evm/keeper/statedb_test.go
x/evm/keeper/utils_test.go

This PR includes the changes to migrate the vesting precompiled tests to the sdk v0.50.
```
❯ go clean --testcache &&  go test ./precompiles/vesting/...
ok      github.com/evmos/evmos/v16/precompiles/vesting  7.918s
```
To achieve this, some changes were necessary on the network setup of the integration tests suite.
For that reason, some of the already migrated tests needed small fixes.
Closes: ENG-2543
---
I have...
I have...

chore(tests): migrate vesting precompile tests

---

CHANGELOG.md
local_node.sh

This PR adds a minor improvement to the local node script. Prior, the total supply was hardcoded and would have to be updated manually if either the genesis accounts or their corresponding balances were changed.

chore(tests): Remove configuration for deprecated modules from local node script

---

CHANGELOG.md
app/ante/evm/04_validate.go
app/ante/evm/04_validate_test.go
app/ante/evm/mono.go

This PR addresses some minor things, that I noticed when reading through the open issues. #2416 pointed at the implementation of validating the `From` address in an Ethereum transaction.
Even though the actual logic is correct, because of the wiring of the ante handler, I agree that the naming of the functions make it "sound" different from what it's doing. Therefore I've adjusted the comments and removed an unnecessary utility function to make the code more readable.
---
I have...
I …

imp(ante): Minor improvements to readibility

---

x/evm/keeper/grpc_query.go
x/evm/keeper/grpc_query_test.go

Currently, the ValidatorAccount query responds with the validator account address (the one has the `evmos` prefix, NOT the `evmosvaloper` prefix). See here [this diff](https://github.com/evmos/evmos/pull/2338/files#diff-16342075507fdd6168b893a629ec4088f1c8ab545f54e7c5b22367d8581e679c) when merged the evm refactor
This PR fixes this issue to avoid changing the API. So the query returns the `AccAddress` as expected
Closes: #XXXX
---
I have...
I have...

fix(grpc): account address return in ValidatorAccount query response

---

README.md

This minor PR removes the mention of the outdated SDK mail address in favor of the os@evmos.org address.

only use os mail address for inquiries

---

app/app.go
app/forks.go
app/upgrades/v17/constants.go
app/upgrades/v17/upgrades.go

Schedule upgrade on block #20_101_000
Closes: #XXXX
---
I have...
I have...

Prepare for v16.0.4

---

.github/workflows/test.yml
app/app.go
app/forks.go
app/upgrades/v18/constants.go
app/upgrades/v18/upgrades.go
mlc_config.json
x/evm/statedb/statedb.go

---
Upgrade handler for v18. 
I have...
I have...

v18.0.0 upgrade logic

---

CHANGELOG.md
app/app.go
x/erc20/keeper/evm_hooks.go
x/erc20/keeper/evm_hooks_test.go
x/erc20/types/events.go

erc20 evm hooks where deleted prior to STRV2, we need to re introduce them, since they are needed for migration logic
Closes: #XXXX
---
I have...
I have...

chore(erc20): re-add deleted erc20 evm hooks

---

CHANGELOG.md
x/erc20/client/cli/tx.go

re-introduce the convert coin txns that was deleted ahead of strv2, but its still needed 
removed on pr https://github.com/evmos/evmos/pull/2155
Closes: #XXXX
---
I have...
I have...

chore(cli): re-introduce convert coin txn for erc20 module

---

CHANGELOG.md
ibc/utils.go
ibc/utils_test.go
x/erc20/keeper/ibc_callbacks.go

Repeated parsing of packetData
The packetData has already been parsed in ibc_callbacks.go, so it is better to pass data into the method to reduce repetitive parsing
https://github.com/evmos/evmos/blob/5a5278898c1795f8f9d140a131398578564c75e8/x/erc20/keeper/ibc_callbacks.go#L40-L46
Closes: #XXXX
---
I have...
I have...

refactor: Repeated parsing of packetData

---

CHANGELOG.md
rpc/backend/backend_suite_test.go
rpc/backend/node_info.go
rpc/backend/sign_tx.go
server/config/config.go
server/config/toml.go
server/flags/flags.go
server/start.go
tests/nix_tests/configs/default.jsonnet

Closes: #XXXX
---
I have...
I have...

feat(jsonrpc): add support for allow-insecure-unlock (#2375)

---

precompiles/distribution/events_test.go
precompiles/distribution/types.go
precompiles/staking/tx_test.go

We may modify the Bech32Prefix, which could potentially cause the unit tests of evmos using constants as prefixes to fail.

imp: use config.Bech32Prefix instead of evmos

---

CHANGELOG.md
testutil/integration/evmos/utils/evm.go
testutil/integration/evmos/utils/evm_test.go

This PR adds a utility function to retrieve the ERC-20 balance with the integration test utilities, that is using the `EthCall` method of the EVM module's `QueryClient`.

imp(tests): Add function to get ERC-20 balance to integration utils

---

app/app.go
app/upgrades/v19/upgrades.go
app/upgrades/v19/upgrades_test.go

Change migrations that will be execute:
- Remove base fee logic
- Remove EIPs: evmos_0001 and evmos_0002

remove eip 0001, 0002 and base fee from migration

---

app/ante/evm/interfaces.go
app/ante/evm/mono.go
x/evm/keeper/config.go
x/evm/keeper/fees_test.go
x/evm/keeper/grpc_query.go
x/evm/keeper/grpc_query_test.go
x/evm/keeper/keeper.go
x/evm/keeper/keeper_test.go

In the getFee function we call the GetParams to get the evm denom decimals. But the params are always queried before to get the chain config (EthereumConfig). So this PR introduces the changes to directly pass the params, which are used to get the EthConfig and  the denom decimals. In this way, we just query the params only once instead of twice
Closes: #XXXX
---
I have...
I have...

chore(evm): refactor getBaseFee to avoid redundant call to get params

---

rpc/backend/chain_info.go
rpc/backend/chain_info_test.go
rpc/types/utils.go
x/evm/keeper/abci.go
x/evm/types/events.go

When querying a block via the JSON-RPC, if there's no base fee got from the queryClient because the node was pruned, it [gets the base fee from the feemarket event emitted on begin block](https://github.com/evmos/evmos/blob/48fc61a3ff02b157a9e05fa2cfd57fbcb2b7d47e/rpc/backend/chain_info.go#L71-L85). A potential solution would be to query the evm params at the current height, but could happen that on the block queried, the evm denom decimals param is different than the current. If we want to keep this logic, I propose adding a base fee event on the begin block of the evm module, with the EVM base fee and use that. 
Closes: #XXXX
---
I have... …

add evm base fee event

---

precompiles/staking/utils_test.go
testutil/consumer.go

Add a custom genesis for the consumer chain in staking precompile tests.
The code is largely inspired from Stride implementation of the test suite: https://github.com/Stride-Labs/stride/blob/4cfda614e8fb9664ce72861d32824d72430d4436/app/test_setup.go#L171
```sh
ginkgo -v "./precompiles/staking"
```

chore(tests): add consumer custom genesis

---

app/ante/evm/06_account_verification_test.go
app/ante/evm/suite_test.go

Add support for custom decimals to account verification
To test fixed ante:
```go
go test -v -tags=test ./app/ante/evm -run ^TestEvmAnteTestSuite$ -testify.m TestVerifyAccountBalance
```
Closes: #ENG-2689

fix(test): Verify account balance ante fix tests
